// client/src/components/session/AutocompletePopup.vue
<script setup lang="ts">
import { computed } from "vue";
import { AlertCircle, Bot, FileText, Folder, LoaderCircle, Terminal } from "lucide-vue-next";
import type { AutocompleteItem } from "@/composables/use-autocomplete";

defineOptions({
  name: "AutocompletePopup",
});

interface AutocompletePopupProps {
  open: boolean;
  items: AutocompleteItem[];
  isLoading: boolean;
  selectedValue: string | null;
  error?: string;
  onSelect: (value: string) => void;
}

interface ItemGroup {
  key: AutocompleteItem["group"];
  label: string;
  items: AutocompleteItem[];
}

const props = defineProps<AutocompletePopupProps>();

const groupDefinitions: ReadonlyArray<{ key: AutocompleteItem["group"]; label: string }> = [
  { key: "command", label: "Commands" },
  { key: "agent", label: "Agents" },
  { key: "file", label: "Files" },
];

const groupedItems = computed<ItemGroup[]>(() => {
  return groupDefinitions
    .map((groupDefinition) => ({
      key: groupDefinition.key,
      label: groupDefinition.label,
      items: props.items.filter((item) => item.group === groupDefinition.key),
    }))
    .filter((group) => group.items.length > 0);
});

function isSelected(item: AutocompleteItem): boolean {
  return item.value === props.selectedValue;
}

function handleItemMouseDown(event: MouseEvent): void {
  event.preventDefault();
}

function handleSelect(value: string): void {
  props.onSelect(value);
}
</script>

<template>
  <div
    v-if="open"
    class="autocomplete-popup"
    role="listbox"
    aria-label="Autocomplete suggestions"
  >
    <div
      v-if="isLoading"
      class="autocomplete-popup__state"
    >
      <LoaderCircle
        class="autocomplete-popup__spinner"
        aria-hidden="true"
      />
      <span>Loading suggestions…</span>
    </div>

    <div
      v-else-if="error"
      class="autocomplete-popup__state autocomplete-popup__state--error"
      role="alert"
    >
      <AlertCircle
        class="autocomplete-popup__state-icon"
        aria-hidden="true"
      />
      <span>{{ error }}</span>
    </div>

    <div
      v-else-if="groupedItems.length === 0"
      class="autocomplete-popup__state"
    >
      No results
    </div>

    <div v-else>
      <section
        v-for="group in groupedItems"
        :key="group.key"
        class="autocomplete-popup__group"
      >
        <div class="autocomplete-popup__group-label">
          {{ group.label }}
        </div>

        <button
          v-for="item in group.items"
          :key="item.id"
          type="button"
          class="autocomplete-popup__item"
          :class="{ 'autocomplete-popup__item--selected': isSelected(item) }"
          :aria-selected="isSelected(item)"
          @mousedown="handleItemMouseDown"
          @click="handleSelect(item.value)"
        >
          <span class="autocomplete-popup__icon-wrap">
            <Terminal
              v-if="item.group === 'command'"
              class="autocomplete-popup__icon"
              aria-hidden="true"
            />

            <span
              v-else-if="item.group === 'agent'"
              class="autocomplete-popup__agent-icon-wrap"
            >
              <Bot
                class="autocomplete-popup__icon"
                aria-hidden="true"
              />
              <span
                v-if="item.meta"
                class="autocomplete-popup__agent-dot"
                :style="{ backgroundColor: item.meta }"
                aria-hidden="true"
              />
            </span>

            <Folder
              v-else-if="item.meta === 'dir'"
              class="autocomplete-popup__icon"
              aria-hidden="true"
            />

            <FileText
              v-else
              class="autocomplete-popup__icon"
              aria-hidden="true"
            />
          </span>

          <span class="autocomplete-popup__content">
            <span class="autocomplete-popup__label">{{ item.label }}</span>
            <span
              v-if="item.description"
              class="autocomplete-popup__description"
            >{{ item.description }}</span>
          </span>
        </button>
      </section>
    </div>
  </div>
</template>

<style scoped>
.autocomplete-popup {
  position: absolute;
  right: 0;
  bottom: calc(100% + 8px);
  left: 0;
  max-height: 300px;
  overflow-y: auto;
  overscroll-behavior: contain;
  scrollbar-gutter: stable;
  border: 1px solid var(--border);
  border-radius: 12px;
  background: var(--card-bg);
  box-shadow: 0 10px 30px rgba(0, 0, 0, 0.3);
  z-index: 250;
}

.autocomplete-popup__group + .autocomplete-popup__group {
  border-top: 1px solid var(--border);
}

.autocomplete-popup__group-label {
  position: sticky;
  top: 0;
  padding: 8px 12px 6px;
  background: var(--card-bg);
  color: var(--muted);
  font-size: 11px;
  font-weight: 600;
  letter-spacing: 0.04em;
  text-transform: uppercase;
}

.autocomplete-popup__item {
  display: flex;
  width: 100%;
  align-items: flex-start;
  gap: 10px;
  padding: 9px 12px;
  border: 0;
  background: transparent;
  color: inherit;
  cursor: pointer;
  text-align: left;
}

.autocomplete-popup__item:hover,
.autocomplete-popup__item--selected {
  background: color-mix(in srgb, var(--accent) 14%, transparent);
}

.autocomplete-popup__item:focus-visible {
  outline: 2px solid var(--accent);
  outline-offset: -2px;
}

.autocomplete-popup__icon-wrap,
.autocomplete-popup__agent-icon-wrap {
  position: relative;
  display: inline-flex;
  flex-shrink: 0;
  align-items: center;
  justify-content: center;
  width: 18px;
  height: 18px;
  margin-top: 1px;
}

.autocomplete-popup__icon {
  width: 16px;
  height: 16px;
  color: var(--muted);
}

.autocomplete-popup__agent-dot {
  position: absolute;
  right: -1px;
  bottom: -1px;
  width: 7px;
  height: 7px;
  border: 1px solid var(--card-bg);
  border-radius: 999px;
}

.autocomplete-popup__content {
  display: flex;
  min-width: 0;
  flex: 1;
  flex-direction: column;
  gap: 2px;
}

.autocomplete-popup__label {
  color: var(--text);
  font-size: 12px;
  font-weight: 600;
  line-height: 1.4;
  word-break: break-word;
}

.autocomplete-popup__description {
  color: var(--muted);
  font-size: 11px;
  line-height: 1.4;
  word-break: break-word;
}

.autocomplete-popup__state {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 8px;
  padding: 14px 16px;
  color: var(--muted);
  font-size: 12px;
  text-align: center;
}

.autocomplete-popup__state--error {
  color: var(--error);
}

.autocomplete-popup__state-icon,
.autocomplete-popup__spinner {
  width: 16px;
  height: 16px;
  flex-shrink: 0;
}

.autocomplete-popup__spinner {
  animation: autocomplete-popup-spin 1s linear infinite;
}

@keyframes autocomplete-popup-spin {
  from {
    transform: rotate(0deg);
  }

  to {
    transform: rotate(360deg);
  }
}
</style>

// client/src/components/session/autocomplete-popup.tsx
"use client";

import * as React from "react";
import {
  Command,
  CommandEmpty,
  CommandGroup,
  CommandItem,
  CommandList,
  CommandSeparator,
} from "@/components/ui/command";
import { Terminal, FileText, Folder, Bot, Loader2 } from "lucide-react";
import { cn } from "@/lib/utils";

export type AutocompleteItemGroup = "command" | "file" | "agent";

export interface AutocompleteItem {
  id: string;
  label: string;
  description?: string;
  group: AutocompleteItemGroup;
  /** The string value inserted into the input on selection */
  value: string;
  /**
   * Optional group-specific metadata:
   * - agents: CSS color string for the colored dot
   * - files:  "dir" if the path is a directory
   */
  meta?: string;
}

interface AutocompletePopupProps {
  open: boolean;
  onSelect: (value: string) => void;
  items: AutocompleteItem[];
  isLoading: boolean;
  /** The value of the currently highlighted item (drives cmdk selection) */
  selectedValue: string | null;
  /** Network / data error to display inline */
  error?: string;
}

const GROUP_LABELS: Record<AutocompleteItemGroup, string> = {
  command: "Commands",
  file: "Files",
  agent: "Agents",
};

const GROUP_ORDER: AutocompleteItemGroup[] = ["command", "agent", "file"];

function ItemIcon({ item }: { item: AutocompleteItem }) {
  if (item.group === "command") {
    return <Terminal className="h-3.5 w-3.5 shrink-0 text-muted-foreground" />;
  }
  if (item.group === "agent") {
    return (
      <span className="relative inline-flex shrink-0 items-center justify-center">
        <Bot className="h-3.5 w-3.5 text-muted-foreground" />
        {item.meta && (
          <span
            className="absolute -right-0.5 -top-0.5 h-1.5 w-1.5 rounded-full"
            style={{ backgroundColor: item.meta }}
          />
        )}
      </span>
    );
  }
  // file group — distinguish directories by meta
  if (item.meta === "dir") {
    return <Folder className="h-3.5 w-3.5 shrink-0 text-muted-foreground" />;
  }
  return <FileText className="h-3.5 w-3.5 shrink-0 text-muted-foreground" />;
}

/**
 * Floating autocomplete popup that renders above the prompt input.
 * Positioned absolutely — the parent container must be `position: relative`.
 *
 * Uses cmdk for keyboard-navigable list semantics.
 * Selection highlighting is driven externally via `selectedValue`.
 */
export function AutocompletePopup({
  open,
  onSelect,
  items,
  isLoading,
  selectedValue,
  error,
}: AutocompletePopupProps) {
  if (!open) return null;

  // Group items by type, preserving GROUP_ORDER
  const grouped = GROUP_ORDER.reduce<Record<AutocompleteItemGroup, AutocompleteItem[]>>(
    (acc, g) => {
      acc[g] = items.filter((item) => item.group === g);
      return acc;
    },
    { command: [], file: [], agent: [] }
  );

  const visibleGroups = GROUP_ORDER.filter((g) => grouped[g].length > 0);
  const hasItems = visibleGroups.length > 0;

  return (
    <div
      role="presentation"
      className={cn(
        "absolute bottom-full left-0 right-0 mb-1 z-50",
        "rounded-md border bg-popover shadow-md overflow-hidden"
      )}
      // Prevent mousedown from blurring the input (allows click-to-select)
      onMouseDown={(e) => e.preventDefault()}
    >
      <Command
        shouldFilter={false}
        value={selectedValue ?? ""}
        className="rounded-none border-0"
      >
        <CommandList id="autocomplete-listbox" className="max-h-[300px]">
          {/* Loading state */}
          {isLoading && (
            <div className="flex items-center justify-center gap-2 py-4 text-xs text-muted-foreground">
              <Loader2 className="h-3.5 w-3.5 animate-spin" />
              <span>Searching…</span>
            </div>
          )}

          {/* Error state */}
          {error && !isLoading && (
            <div role="alert" className="px-3 py-2 text-xs text-red-600 dark:text-red-400">
              {error}
            </div>
          )}

          {/* Empty state — only when not loading and no error */}
          {!isLoading && !error && !hasItems && (
            <CommandEmpty className="py-4 text-xs">No results</CommandEmpty>
          )}

          {/* Grouped items */}
          {!isLoading &&
            visibleGroups.map((group, groupIndex) => (
              <React.Fragment key={group}>
                {groupIndex > 0 && <CommandSeparator />}
                <CommandGroup heading={GROUP_LABELS[group]}>
                  {grouped[group].map((item) => (
                    <CommandItem
                      key={item.id}
                      id={`autocomplete-item-${item.value}`}
                      value={item.value}
                      onSelect={() => onSelect(item.value)}
                      className="gap-2 text-sm"
                    >
                      <ItemIcon item={item} />
                      <span className="truncate font-medium">{item.label}</span>
                      {item.description && (
                        <span className="ml-auto truncate text-xs text-muted-foreground">
                          {item.description}
                        </span>
                      )}
                    </CommandItem>
                  ))}
                </CommandGroup>
              </React.Fragment>
            ))}
        </CommandList>
      </Command>
    </div>
  );
}
