// client/src/components/session/fork-session-dialog.tsx

import { useState, useRef } from "react";
import { useNavigate } from "react-router";
import { Loader2, AlertCircle, GitFork } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { useForkSession } from "@/hooks/use-fork-session";
import { useSessionsContext } from "@/contexts/sessions-context";

interface ForkSessionDialogProps {
  /** Fleet DB id or opencode session id of the session to fork */
  sourceSessionId: string;
  /** Human-readable title of the source session — shown in the dialog */
  sourceSessionTitle?: string;
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

export function ForkSessionDialog({
  sourceSessionId,
  sourceSessionTitle,
  open,
  onOpenChange,
}: ForkSessionDialogProps) {
  const navigate = useNavigate();
  const [title, setTitle] = useState("");
  const { forkSession, clearError, isForking, error } = useForkSession();
  const { refetch } = useSessionsContext();
  const inputRef = useRef<HTMLInputElement>(null);

  const handleClose = (value: boolean) => {
    if (!value) {
      setTitle("");
      clearError();
    }
    onOpenChange(value);
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (isForking) return;

    try {
      const { instanceId, session } = await forkSession(sourceSessionId, {
        title: title.trim() || undefined,
      });
      handleClose(false);
      refetch();
      navigate(
        `/sessions/${encodeURIComponent(session.id)}?instanceId=${encodeURIComponent(instanceId)}`
      );
    } catch {
      // error is already set by useForkSession
    }
  };

  return (
    <Dialog open={open} onOpenChange={handleClose}>
      <DialogContent
        data-testid="fork-session-dialog"
        className="sm:max-w-sm top-[10%] translate-y-0 max-h-[85vh] overflow-y-auto"
        onOpenAutoFocus={(e) => {
          // Prevent Radix from focusing the first focusable element (the close
          // button) and instead focus the title input directly.
          e.preventDefault();
          inputRef.current?.focus();
        }}
      >
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <GitFork className="h-4 w-4" />
            <span data-testid="fork-session-dialog-title">New Context Window</span>
          </DialogTitle>
        </DialogHeader>

        <form onSubmit={handleSubmit} className="space-y-4">
          {sourceSessionTitle && (
            <p className="text-sm text-muted-foreground">
              Creates a fresh session in the same workspace as{" "}
                <span className="font-medium text-foreground">
                  <span data-testid="fork-session-source-title">{sourceSessionTitle}</span>
                </span>
              .
            </p>
          )}

          <div className="space-y-1.5">
            <label className="text-sm font-medium" htmlFor="fork-session-title">
              Title{" "}
              <span className="text-muted-foreground font-normal">(optional)</span>
            </label>
            <Input
              ref={inputRef}
              data-testid="fork-session-title-input"
              id="fork-session-title"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              placeholder="What are you working on?"
              disabled={isForking}
            />
          </div>

          {error && (
            <div className="flex items-start gap-2 rounded-md bg-red-500/10 border border-red-500/20 px-3 py-2 text-xs text-red-600 dark:text-red-400">
              <AlertCircle className="h-3.5 w-3.5 mt-0.5 shrink-0" />
              <span>{error}</span>
            </div>
          )}

          <div className="flex justify-end gap-2">
            <Button
              type="button"
              variant="ghost"
              size="sm"
              onClick={() => handleClose(false)}
              disabled={isForking}
            >
              Cancel
            </Button>
            <Button
              type="submit"
              data-testid="fork-session-submit"
              size="sm"
              className="weave-gradient-bg hover:opacity-90 border-0"
              disabled={isForking}
            >
              {isForking ? (
                <>
                  <Loader2 className="h-3.5 w-3.5 animate-spin mr-1.5" />
                  Forking…
                </>
              ) : (
                "New Context Window"
              )}
            </Button>
          </div>
        </form>
      </DialogContent>
    </Dialog>
  );
}

// client/src/components/session/ForkSessionDialog.vue
<script setup lang="ts">
import { computed, shallowRef, watch } from "vue";
import { useRouter } from "@tanstack/vue-router";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { useForkSession } from "@/composables/use-session-actions";

interface Props {
  sessionId: string;
  sourceTitle: string;
  open?: boolean;
}

const props = withDefaults(defineProps<Props>(), {
  open: false,
});
const emit = defineEmits<{
  "update:open": [value: boolean];
}>();

const router = useRouter();
const title = shallowRef("");
const { forkSession, clearError, isForking, error } = useForkSession();

const resolvedSourceTitle = computed(() => props.sourceTitle.trim() || "Untitled session");

function resetForm(): void {
  title.value = resolvedSourceTitle.value;
}

function handleOpenChange(value: boolean): void {
  emit("update:open", value);
}

async function handleSubmit(): Promise<void> {
  try {
    const response = await forkSession(props.sessionId, {
      title: title.value.trim() || undefined,
    });

    emit("update:open", false);

    await router.navigate({
      to: "/sessions/$id",
      params: { id: response.session.id },
      search: {
        instanceId: response.instanceId,
        parentSessionId: undefined,
      },
    });
  } catch {
    // Error exposed via composable state.
  }
}

watch(
  [() => props.open, resolvedSourceTitle],
  ([isOpen]) => {
    clearError();

    if (isOpen) {
      resetForm();
      return;
    }

    resetForm();
  },
  { immediate: true },
);
</script>

<template>
  <Dialog :open="props.open" @update:open="handleOpenChange">
    <DialogContent class="sm:max-w-lg" data-testid="fork-session-dialog">
      <DialogHeader>
        <DialogTitle data-testid="fork-session-dialog-title">
          Fork Session
        </DialogTitle>
      </DialogHeader>

      <form class="space-y-4" @submit.prevent="void handleSubmit()">
        <div class="space-y-2">
          <p class="text-sm font-medium text-foreground">Source session</p>
          <p data-testid="fork-session-source-title" class="text-sm text-muted-foreground">
            {{ resolvedSourceTitle }}
          </p>
        </div>

        <div class="space-y-2">
          <label for="fork-session-title" class="text-sm font-medium text-foreground">
            New session title
          </label>
          <Input
            id="fork-session-title"
            v-model="title"
            data-testid="fork-session-title-input"
            placeholder="Enter a title"
            :disabled="isForking"
          />
        </div>

        <p
          v-if="error"
          class="rounded-lg border border-destructive/30 bg-destructive/10 px-3 py-2 text-sm text-destructive"
          role="alert"
        >
          {{ error }}
        </p>

        <DialogFooter>
          <Button
            data-testid="fork-session-submit"
            type="submit"
            :disabled="isForking"
          >
            {{ isForking ? "Forking…" : "Fork session" }}
          </Button>
        </DialogFooter>
      </form>
    </DialogContent>
  </Dialog>
</template>
