// client/src/components/session/new-session-dialog.tsx
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import type { ReactNode } from "react";
import { useNavigate } from "react-router";
import { AlertCircle, CheckCircle2, ExternalLink, Loader2, XCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { SourcePicker } from "@/components/session/sources/source-picker";
import {
  RepositorySourceForm,
  type RepositoryIsolationStrategy,
} from "@/components/session/sources/repository-source-form";
import { DirectorySourceForm } from "@/components/session/sources/directory-source-form";
import { useCreateSession } from "@/hooks/use-create-session";
import { useAddSourceToSession } from "@/hooks/use-add-source-to-session";
import { useSessionsContext } from "@/contexts/sessions-context";
import { useHarnesses } from "@/hooks/use-harnesses";
import { usePersistedState } from "@/hooks/use-persisted-state";
import { useRepositories } from "@/hooks/use-repositories";
import { useProjects } from "@/hooks/use-projects";
import { useSessionSources } from "@/session-sources/use-session-sources";
import { DEFAULT_HARNESS_KEY } from "@/components/settings/harnesses-tab";
import { useAppShell } from "@/contexts/app-shell-context";
import type {
  ProjectResponse,
  ScannedRepository,
  SessionSourceSelection,
} from "@/lib/api-types";
import type { RegisteredSessionSource } from "@/session-sources/types";

const UNGROUPED_VALUE = "__ungrouped__";
const REPOSITORY_SOURCE_ID = "builtin.repository:repository";
const DIRECTORY_SOURCE_ID = "builtin.local:directory";
const MANAGED_SOURCE_ID = "builtin.managed:managed-workspace";

interface NewSessionDialogProps {
  trigger?: ReactNode;
  open?: boolean;
  onOpenChange?: (open: boolean) => void;
  defaultDirectory?: string;
  userProjects?: ProjectResponse[];
  initialSource?: SessionSourceSelection;
  initialTitle?: string;
}

function makeSourceId(source: RegisteredSessionSource): string {
  return `${source.descriptor.key.providerId}:${source.descriptor.key.sourceType}`;
}

function generateBranchName(text: string): string {
  return text
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9\s-]/g, "")
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "");
}

export function NewSessionDialog({ trigger, open: controlledOpen, onOpenChange, defaultDirectory, userProjects: userProjectsProp, initialSource, initialTitle }: NewSessionDialogProps) {
  const navigate = useNavigate();
  const { clientConfig } = useAppShell();
  const [internalOpen, setInternalOpen] = useState(false);
  const open = controlledOpen ?? internalOpen;

  const [directory, setDirectory] = usePersistedState("weave:new-session:lastDirectory", "");
  const [title, setTitle] = useState("");
  const [branch, setBranch] = useState("");
  const [branchManuallyEdited, setBranchManuallyEdited] = useState(false);
  const [selectedProjectId, setSelectedProjectId] = useState<string>(UNGROUPED_VALUE);
  const [selectedHarness, setSelectedHarness] = useState("");
  const [selectedSourceId, setSelectedSourceId] = useState<string | null>(defaultDirectory ? DIRECTORY_SOURCE_ID : null);

  const [selectedRepo, setSelectedRepo] = useState<ScannedRepository | null>(null);
  const [repoSearch, setRepoSearch] = useState("");
  const [repoDropdownOpen, setRepoDropdownOpen] = useState(false);
  const [repoHighlightIdx, setRepoHighlightIdx] = useState(0);
  const [repoStrategy, setRepoStrategy] = useState<RepositoryIsolationStrategy>("worktree");
  const repoInputRef = useRef<HTMLInputElement>(null);
  const repoListRef = useRef<HTMLDivElement>(null);

  const { repositories, isLoading: repositoriesLoading, refresh: refreshRepositories } = useRepositories();
  const { sources, isLoading: sourcesLoading, error: sourcesError } = useSessionSources();
  const { createSession, isLoading, error } = useCreateSession();
  const { addSourceToSession, isLoading: isAddingSource, error: addSourceError } = useAddSourceToSession();
  const { refetch } = useSessionsContext();
  const { harnesses, isLoading: harnessesLoading } = useHarnesses();
  const [defaultHarness] = usePersistedState<string>(DEFAULT_HARNESS_KEY, "opencode");

  const { projects } = useProjects({ enabled: !userProjectsProp });
  const userProjects = userProjectsProp ?? projects.filter((project) => project.type !== "scratch");
  const showProjectPicker = userProjects.length > 0;
  const showHarnessPicker = harnesses.length >= 2;
  const availableHarnesses = harnesses.filter((harness) => harness.available);
  const isCloudMode = clientConfig.cloudMode;

  useEffect(() => {
    if (open) {
      void refreshRepositories();
    }
  }, [open, refreshRepositories]);

  const resolvedHarness = useMemo(() => {
    if (selectedHarness && harnesses.some((h) => h.type === selectedHarness)) {
      return selectedHarness;
    }

    if (harnesses.length === 0) {
      return "";
    }

    const defaultAvailable = availableHarnesses.find((harness) => harness.type === defaultHarness);
    return defaultAvailable?.type ?? availableHarnesses[0]?.type ?? "opencode";
  }, [availableHarnesses, defaultHarness, harnesses, selectedHarness]);

  const filteredRepos = useMemo(() => {
    if (!repoSearch.trim()) {
      return repositories;
    }

    const query = repoSearch.toLowerCase();
    return repositories.filter(
      (repo) => repo.name.toLowerCase().includes(query) || repo.path.toLowerCase().includes(query)
    );
  }, [repositories, repoSearch]);

  useEffect(() => {
    if (repoDropdownOpen && repoListRef.current) {
      const highlighted = repoListRef.current.children[repoHighlightIdx] as HTMLElement | undefined;
      highlighted?.scrollIntoView({ block: "nearest" });
    }
  }, [repoDropdownOpen, repoHighlightIdx]);

  const resolvedSourceId = useMemo(() => {
    if (selectedSourceId) {
      return selectedSourceId;
    }

    if (sources.length === 0) {
      return null;
    }

    const defaultSource = isCloudMode
      ? sources.find((source) => makeSourceId(source) === MANAGED_SOURCE_ID)
        ?? sources.find((source) => makeSourceId(source) === REPOSITORY_SOURCE_ID)
        ?? sources[0]
      : defaultDirectory
        ? sources.find((source) => makeSourceId(source) === DIRECTORY_SOURCE_ID)
        : sources.find((source) => makeSourceId(source) === REPOSITORY_SOURCE_ID) ?? sources[0];

    return defaultSource ? makeSourceId(defaultSource) : null;
  }, [defaultDirectory, isCloudMode, selectedSourceId, sources]);

  const resolvedBranch = resolvedSourceId === REPOSITORY_SOURCE_ID && !branchManuallyEdited
    ? generateBranchName(title)
    : branch;

  const resolvedRepo = useMemo(() => {
    if (resolvedSourceId !== REPOSITORY_SOURCE_ID || repositoriesLoading || repositories.length === 0) {
      return selectedRepo;
    }

    return selectedRepo ?? repositories[0];
  }, [repositories, repositoriesLoading, selectedRepo, resolvedSourceId]);

  const resolvedRepoSearch = !selectedRepo && resolvedRepo ? resolvedRepo.name : repoSearch;

  const selectedSource = useMemo(
    () => sources.find((source) => makeSourceId(source) === resolvedSourceId) ?? null,
    [resolvedSourceId, sources]
  );

  const isRepositorySource = resolvedSourceId === REPOSITORY_SOURCE_ID;
  const isDirectorySource = resolvedSourceId === DIRECTORY_SOURCE_ID;
  const isManagedSource = resolvedSourceId === MANAGED_SOURCE_ID;
  const visibleSources = useMemo(() => sources.filter((source) => {
    const sourceId = makeSourceId(source);
    if (sourceId === REPOSITORY_SOURCE_ID || sourceId === MANAGED_SOURCE_ID) {
      return true;
    }

    if (sourceId === DIRECTORY_SOURCE_ID) {
      return !isCloudMode;
    }

    return false;
  }), [isCloudMode, sources]);

  const effectiveDirectory = isRepositorySource
    ? resolvedRepo?.path ?? ""
    : (defaultDirectory || directory).trim();

  const effectiveSourceSelection = useMemo<SessionSourceSelection | undefined>(() => {
    if (isRepositorySource && resolvedRepo) {
      return {
        key: {
          providerId: "builtin.repository",
          sourceType: "repository",
          actionId: "start-session",
          contractVersion: 1,
        },
        input: {
          repositoryPath: resolvedRepo.path,
          isolationStrategy: repoStrategy,
          ...(repoStrategy === "worktree" && resolvedBranch.trim() ? { branch: resolvedBranch.trim() } : {}),
        },
      };
    }

    if (isDirectorySource && (defaultDirectory || directory).trim()) {
      return {
        key: {
          providerId: "builtin.local",
          sourceType: "directory",
          actionId: "start-session",
          contractVersion: 1,
        },
        input: {
          directory: (defaultDirectory || directory).trim(),
          isolationStrategy: "existing",
        },
      };
    }

    if (isCloudMode && isManagedSource) {
      return {
        key: {
          providerId: "builtin.managed",
          sourceType: "managed-workspace",
          actionId: "start-session",
          contractVersion: 1,
        },
        input: {},
      };
    }

    return undefined;
  }, [resolvedBranch, defaultDirectory, directory, isCloudMode, isDirectorySource, isManagedSource, isRepositorySource, repoStrategy, resolvedRepo]);

  const canSubmit = Boolean((isCloudMode || effectiveDirectory) && selectedSource && effectiveSourceSelection) && !isLoading && !isAddingSource;

  const handleRepoSelect = useCallback((repo: ScannedRepository) => {
    setSelectedRepo(repo);
    setRepoSearch(repo.name);
    setRepoDropdownOpen(false);
  }, []);

  const handleRepoBlur = useCallback(() => {
    setTimeout(() => {
      if (filteredRepos.length === 1) {
        handleRepoSelect(filteredRepos[0]);
      } else if (selectedRepo && repoSearch !== selectedRepo.name) {
        const stillMatches = filteredRepos.find((repo) => repo.path === selectedRepo.path);
        if (stillMatches) {
          setRepoSearch(selectedRepo.name);
        } else {
          setSelectedRepo(null);
        }
      }

      setRepoDropdownOpen(false);
    }, 150);
  }, [filteredRepos, handleRepoSelect, repoSearch, selectedRepo]);

  const handleRepoKeyDown = useCallback((event: React.KeyboardEvent<HTMLInputElement>) => {
    if (!repoDropdownOpen && (event.key === "ArrowDown" || event.key === "ArrowUp")) {
      setRepoDropdownOpen(true);
      event.preventDefault();
      return;
    }

    if (event.key === "ArrowDown") {
      event.preventDefault();
      setRepoHighlightIdx((current) => Math.min(current + 1, filteredRepos.length - 1));
    } else if (event.key === "ArrowUp") {
      event.preventDefault();
      setRepoHighlightIdx((current) => Math.max(current - 1, 0));
    } else if (event.key === "Enter" && repoDropdownOpen) {
      event.preventDefault();
      const highlighted = filteredRepos[repoHighlightIdx];
      if (highlighted) {
        handleRepoSelect(highlighted);
      }
    }
  }, [filteredRepos, handleRepoSelect, repoDropdownOpen, repoHighlightIdx]);

  const resetState = useCallback(() => {
    setTitle("");
    setBranch("");
    setBranchManuallyEdited(false);
    setSelectedRepo(null);
    setRepoSearch("");
    setRepoDropdownOpen(false);
    setRepoStrategy("worktree");
    setSelectedHarness("");
    setSelectedProjectId(UNGROUPED_VALUE);
    setSelectedSourceId(defaultDirectory && !isCloudMode ? DIRECTORY_SOURCE_ID : null);
  }, [defaultDirectory, isCloudMode]);

  const setOpen = useCallback((value: boolean) => {
    if (!value) {
      resetState();
    }

    setInternalOpen(value);
    onOpenChange?.(value);
  }, [onOpenChange, resetState]);

  const handleSubmit = useCallback(async (event: React.FormEvent) => {
    event.preventDefault();
    if (!effectiveSourceSelection || isLoading || isAddingSource || (!isCloudMode && !effectiveDirectory)) {
      return;
    }

    try {
      const { instanceId, session } = await createSession(isCloudMode ? undefined : effectiveDirectory, {
        title: (title || initialTitle || "").trim() || undefined,
        source: effectiveSourceSelection,
        harnessType: showHarnessPicker ? resolvedHarness : undefined,
        projectId: selectedProjectId !== UNGROUPED_VALUE ? selectedProjectId : undefined,
      });

      if (initialSource) {
        await addSourceToSession(session.id, initialSource, true);
      }

      setOpen(false);
      refetch();
      navigate(`/sessions/${encodeURIComponent(session.id)}?instanceId=${encodeURIComponent(instanceId)}`);
    } catch {
      // handled by hook state
    }
  }, [
    createSession,
    effectiveDirectory,
    effectiveSourceSelection,
    isLoading,
    navigate,
    refetch,
    addSourceToSession,
    resolvedHarness,
    selectedProjectId,
    setOpen,
    showHarnessPicker,
    title,
    initialTitle,
    initialSource,
    isAddingSource,
    isCloudMode,
  ]);

  const sourceError = error ?? addSourceError ?? sourcesError;

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      {trigger ? <DialogTrigger asChild>{trigger}</DialogTrigger> : null}
      <DialogContent data-testid="new-session-dialog" className="sm:max-w-md top-[10%] translate-y-0 max-h-[85vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>New Session</DialogTitle>
        </DialogHeader>

        <form onSubmit={handleSubmit} className="space-y-4">
          <SourcePicker
            sources={visibleSources}
            selectedSourceId={resolvedSourceId}
            isLoading={isLoading || sourcesLoading}
            isSourceDisabled={(source) => makeSourceId(source) === REPOSITORY_SOURCE_ID && repositories.length === 0}
            helperText={isCloudMode ? "Cloud mode uses managed workspaces automatically. Local directories are unavailable." : undefined}
            onSelect={setSelectedSourceId}
          />

          {isRepositorySource ? (
            <RepositorySourceForm
              isLoading={isLoading}
              repositories={repositories}
              filteredRepositories={filteredRepos}
              selectedRepository={resolvedRepo}
              repositorySearch={resolvedRepoSearch}
              repositoryDropdownOpen={repoDropdownOpen}
              repositoryHighlightIndex={repoHighlightIdx}
              repositoryInputRef={repoInputRef}
              repositoryListRef={repoListRef}
              strategy={repoStrategy}
              branch={resolvedBranch}
              branchManuallyEdited={branchManuallyEdited}
              onRepositorySearchChange={(value) => {
                setRepoSearch(value);
                setRepoDropdownOpen(true);
                setRepoHighlightIdx(0);
                if (selectedRepo && value !== selectedRepo.name) {
                  setSelectedRepo(null);
                }
              }}
              onRepositoryFocus={() => setRepoDropdownOpen(true)}
              onRepositoryBlur={handleRepoBlur}
              onRepositoryKeyDown={handleRepoKeyDown}
              onRepositoryHover={setRepoHighlightIdx}
              onRepositorySelect={handleRepoSelect}
              onStrategyChange={setRepoStrategy}
              onBranchChange={(value) => {
                setBranch(value);
                setBranchManuallyEdited(true);
              }}
            />
          ) : null}

          {isDirectorySource ? (
            <DirectorySourceForm
              directory={defaultDirectory || directory}
              isLoading={isLoading}
              onDirectoryChange={setDirectory}
            />
          ) : null}

          {isCloudMode && isManagedSource ? (
            <div className="rounded-md border border-border bg-muted/30 px-3 py-2 text-xs text-muted-foreground">
              Managed workspaces are created automatically in cloud mode. Start a basic session without entering a local directory.
            </div>
          ) : null}

          <div className="space-y-1.5">
            <label className="text-sm font-medium" htmlFor="session-title">
              Title <span className="font-normal text-muted-foreground">(optional)</span>
            </label>
            <Input
              id="session-title"
              value={title}
              onChange={(event) => setTitle(event.target.value)}
              placeholder="What are you working on?"
              disabled={isLoading}
            />
          </div>

          {showProjectPicker ? (
            <div className="space-y-1.5">
              <label className="text-sm font-medium" htmlFor="project-select">
                Project <span className="font-normal text-muted-foreground">(optional)</span>
              </label>
              <Select value={selectedProjectId} onValueChange={setSelectedProjectId} disabled={isLoading}>
                <SelectTrigger id="project-select" className="w-full">
                  <SelectValue placeholder="Ungrouped" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value={UNGROUPED_VALUE}>Ungrouped</SelectItem>
                  {userProjects.map((project) => (
                    <SelectItem key={project.id} value={project.id}>
                      {project.name}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          ) : null}

          {showHarnessPicker ? (
            <div className="space-y-1.5">
              <label className="text-sm font-medium" htmlFor="harness-select">
                Harness
              </label>
              <Select value={resolvedHarness} onValueChange={setSelectedHarness} disabled={isLoading || harnessesLoading}>
                <SelectTrigger id="harness-select" className="w-full">
                  <SelectValue placeholder="Select harness" />
                </SelectTrigger>
                <SelectContent>
                  {harnesses.map((harness) => (
                    <SelectItem key={harness.type} value={harness.type} disabled={!harness.available}>
                      <span className="flex items-center gap-2">
                        {harness.available ? (
                          <CheckCircle2 className="h-3 w-3 text-green-500" />
                        ) : (
                          <XCircle className="h-3 w-3 text-muted-foreground" />
                        )}
                        {harness.displayName}
                      </span>
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          ) : null}

          {sourceError ? (
            <div className="flex items-start gap-2 rounded-md border border-red-500/20 bg-red-500/10 px-3 py-2 text-xs text-red-600 dark:text-red-400">
              <AlertCircle className="mt-0.5 h-3.5 w-3.5 shrink-0" />
              <span>
                {sourceError}
                {isCloudMode && (error ?? addSourceError) ? (
                  <>
                    {" "}
                    <a
                      href="/settings"
                      className="underline underline-offset-2 hover:text-red-700 dark:hover:text-red-300 inline-flex items-center gap-0.5"
                      onClick={() => setOpen(false)}
                    >
                      Add an API key in Settings <ExternalLink className="h-3 w-3" />
                    </a>
                  </>
                ) : null}
              </span>
            </div>
          ) : null}

          <Button type="submit" data-testid="create-session-submit" className="w-full weave-gradient-bg hover:opacity-90 border-0" disabled={!canSubmit}>
            {isLoading || isAddingSource ? (
              <>
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                {isAddingSource ? "Adding context…" : "Spawning…"}
              </>
            ) : (
              "Create Session"
            )}
          </Button>
        </form>
      </DialogContent>
    </Dialog>
  );
}

// client/src/components/sessions/NewSessionDialog.vue
<script setup lang="ts">
import { computed, nextTick, shallowRef, watch } from "vue";
import { AlertCircle, ArrowUp, Check, Folder, FolderGit2, LoaderCircle, RefreshCw } from "lucide-vue-next";
import { storeToRefs } from "pinia";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { useDirectoryBrowser } from "@/composables/use-directory-browser";
import { useHarnesses } from "@/composables/use-harnesses";
import { useProjects } from "@/composables/use-projects";
import { useRepositories } from "@/composables/use-repositories";
import { useCreateSession } from "@/composables/use-session-actions";
import type {
  CreateSessionResponse,
  HarnessInfo,
  ProjectResponse,
  ScannedRepository,
  SessionSourceSelection,
} from "@/lib/api-types";
import { readWorkspacePreferences } from "@/lib/workspace-preferences";
import { useAppShellStore } from "@/stores/app-shell";

type SessionSourceKind = "repository" | "directory";
type IsolationStrategy = "existing" | "worktree" | "clone";

interface Props {
  initialProjectId?: string | null;
}

const UNGROUPED_PROJECT_ID = "__ungrouped__";

const props = withDefaults(defineProps<Props>(), {
  initialProjectId: null,
});

const open = defineModel<boolean>("open", { default: false });

const emit = defineEmits<{
  created: [response: CreateSessionResponse];
}>();

const appShellStore = useAppShellStore();
const { config } = storeToRefs(appShellStore);

const sourceKind = shallowRef<SessionSourceKind>("repository");
const repositoryQuery = shallowRef("");
const selectedRepositoryPath = shallowRef<string | null>(null);
const isRepositoryListOpen = shallowRef(false);
const isDirectoryPickerOpen = shallowRef(false);
const directory = shallowRef("");
const title = shallowRef("");
const isolationStrategy = shallowRef<IsolationStrategy>("worktree");
const branch = shallowRef("");
const branchManuallyEdited = shallowRef(false);
const selectedProjectId = shallowRef(props.initialProjectId ?? UNGROUPED_PROJECT_ID);
const selectedHarnessType = shallowRef("");
const submitAttempted = shallowRef(false);

const {
  repositories,
  isLoading: isRepositoriesLoading,
  error: repositoriesError,
  refresh: refreshRepositories,
} = useRepositories();
const {
  projects,
  error: projectsError,
} = useProjects({ enabled: open });
const {
  harnesses,
  error: harnessesError,
} = useHarnesses();
const {
  createSession,
  isLoading: isCreating,
  error: createError,
} = useCreateSession();
const {
  currentPath: directoryBrowserPath,
  entries: directoryEntries,
  isLoading: isDirectoryBrowserLoading,
  error: directoryBrowserError,
  roots: directoryRoots,
  parentPath: directoryParentPath,
  search: directorySearch,
  browse: browseDirectory,
  goUp: goUpDirectory,
  refresh: refreshDirectoryBrowser,
  setSearch: setDirectorySearch,
  hasActivated: hasActivatedDirectoryBrowser,
} = useDirectoryBrowser();

const userProjects = computed<readonly ProjectResponse[]>(() => {
  return projects.value.filter((project) => project.type !== "scratch");
});

const availableHarnesses = computed<readonly HarnessInfo[]>(() => {
  return harnesses.value.filter((harness) => harness.available);
});

const showHarnessSelect = computed(() => availableHarnesses.value.length > 1);
const showProjectSelect = computed(() => userProjects.value.length > 0);
const isCloudMode = computed(() => config.value.cloudMode);

const sortedRepositories = computed<readonly ScannedRepository[]>(() => {
  return [...repositories.value].sort((left, right) => left.name.localeCompare(right.name));
});

const filteredRepositories = computed<readonly ScannedRepository[]>(() => {
  const query = repositoryQuery.value.trim().toLowerCase();
  if (!query) {
    return sortedRepositories.value;
  }

  return sortedRepositories.value.filter((repository) => {
    const searchableText = `${repository.name} ${repository.path}`.toLowerCase();
    return searchableText.includes(query);
  });
});

const selectedRepository = computed<ScannedRepository | null>(() => {
  if (!selectedRepositoryPath.value) {
    return null;
  }

  return repositories.value.find((repository) => repository.path === selectedRepositoryPath.value) ?? null;
});

const generatedBranch = computed(() => {
  return title.value
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9\s-]/g, "")
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "");
});

const effectiveBranch = computed(() => {
  if (isolationStrategy.value !== "worktree") {
    return "";
  }

  return branchManuallyEdited.value ? branch.value.trim() : generatedBranch.value;
});

const resolvedHarnessType = computed(() => {
  if (selectedHarnessType.value && availableHarnesses.value.some((harness) => harness.type === selectedHarnessType.value)) {
    return selectedHarnessType.value;
  }

  return availableHarnesses.value[0]?.type ?? "";
});

const effectiveDirectory = computed(() => {
  if (sourceKind.value === "repository") {
    return selectedRepository.value?.path ?? "";
  }

  return directory.value.trim();
});

const directoryPickerLocation = computed(() => {
  if (directoryBrowserPath.value) {
    return directoryBrowserPath.value;
  }

  const preferredRoot = getPreferredWorkspaceRoot();
  if (preferredRoot) {
    return preferredRoot;
  }

  return directoryRoots.value[0] ?? "Workspace roots";
});

const sessionSource = computed<SessionSourceSelection | undefined>(() => {
  if (sourceKind.value === "repository") {
    if (!selectedRepository.value) {
      return undefined;
    }

    return {
      key: {
        providerId: "builtin.repository",
        sourceType: "repository",
        actionId: "start-session",
        contractVersion: 1,
      },
      input: {
        repositoryPath: selectedRepository.value.path,
        isolationStrategy: isolationStrategy.value,
        ...(isolationStrategy.value === "worktree" && effectiveBranch.value
          ? { branch: effectiveBranch.value }
          : {}),
      },
    };
  }

  if (!directory.value.trim()) {
    return undefined;
  }

  return {
    key: {
      providerId: "builtin.local",
      sourceType: "directory",
      actionId: "start-session",
      contractVersion: 1,
    },
    input: {
      directory: directory.value.trim(),
      isolationStrategy: "existing",
    },
  };
});

const validationMessage = computed(() => {
  if (sourceKind.value === "repository") {
    if (isRepositoriesLoading.value) {
      return "Loading repositories…";
    }

    if (!selectedRepository.value) {
      return repositories.value.length === 0 ? "No repositories are available." : "Select a repository.";
    }
  }

  if (!isCloudMode.value && sourceKind.value === "directory" && !directory.value.trim()) {
    return "Directory is required.";
  }

  return null;
});

const dialogError = computed(() => {
  if (submitAttempted.value && validationMessage.value) {
    return validationMessage.value;
  }

  return createError.value
    ?? repositoriesError.value
    ?? projectsError.value
    ?? harnessesError.value
    ?? directoryBrowserError.value
    ?? null;
});

const canSubmit = computed(() => {
  return !isCreating.value && sessionSource.value !== undefined && validationMessage.value === null;
});

function getInitialProjectSelection(): string {
  return props.initialProjectId ?? UNGROUPED_PROJECT_ID;
}

function resetForm(): void {
  sourceKind.value = "repository";
  repositoryQuery.value = "";
  selectedRepositoryPath.value = null;
  isRepositoryListOpen.value = false;
  isDirectoryPickerOpen.value = false;
  directory.value = "";
  title.value = "";
  isolationStrategy.value = "worktree";
  branch.value = "";
  branchManuallyEdited.value = false;
  selectedProjectId.value = getInitialProjectSelection();
  selectedHarnessType.value = "";
  submitAttempted.value = false;
}

function selectRepository(repository: ScannedRepository): void {
  selectedRepositoryPath.value = repository.path;
  repositoryQuery.value = repository.path;
  isRepositoryListOpen.value = false;
}

function handleOpenChange(value: boolean): void {
  open.value = value;
}

function handleRepositoryBlur(): void {
  window.setTimeout(() => {
    isRepositoryListOpen.value = false;

    if (selectedRepository.value && repositoryQuery.value.trim() === selectedRepository.value.path) {
      return;
    }

    if (filteredRepositories.value.length === 1) {
      selectRepository(filteredRepositories.value[0]);
      return;
    }

    selectedRepositoryPath.value = null;
  }, 120);
}

function getPreferredWorkspaceRoot(): string {
  if (typeof window === "undefined") {
    return "";
  }

  return readWorkspacePreferences(window.localStorage).preferredRootPath;
}

function getDirectoryBrowserStartPath(): string | null {
  const selectedDirectory = directory.value.trim();
  if (selectedDirectory) {
    return selectedDirectory;
  }

  return getPreferredWorkspaceRoot() || null;
}

function syncDirectoryBrowser(): void {
  const nextPath = getDirectoryBrowserStartPath();
  if (!hasActivatedDirectoryBrowser.value || directoryBrowserPath.value !== nextPath) {
    browseDirectory(nextPath);
  }
}

function openDirectoryPicker(): void {
  syncDirectoryBrowser();
  isDirectoryPickerOpen.value = true;
}

function handleDirectorySelected(path: string): void {
  directory.value = path;
  isDirectoryPickerOpen.value = false;
}

function handleDirectorySearchUpdate(value: string | number): void {
  setDirectorySearch(String(value));
}

function handleDialogInteractOutside(event: Event): void {
  const target = event.target as HTMLElement | null;
  if (target?.closest('[data-slot="popover-content"]')) {
    event.preventDefault();
  }
}

async function handleSubmit(): Promise<void> {
  submitAttempted.value = true;

  if (!canSubmit.value || !sessionSource.value) {
    return;
  }

  try {
    const response = await createSession(effectiveDirectory.value || undefined, {
      title: title.value.trim() || undefined,
      source: sessionSource.value,
      harnessType: resolvedHarnessType.value || undefined,
      projectId: selectedProjectId.value !== UNGROUPED_PROJECT_ID ? selectedProjectId.value : undefined,
    });

    open.value = false;
    emit("created", response);
  } catch {
    // Mutation state drives the dialog error banner.
  }
}

watch(open, async (isOpen) => {
  if (isOpen) {
    submitAttempted.value = false;
    selectedProjectId.value = getInitialProjectSelection();
    void refreshRepositories();
    await nextTick();
    document.getElementById("session-title")?.focus();
    return;
  }

  resetForm();
});

watch(
  [open, sourceKind, repositories],
  ([isOpen, nextSourceKind, nextRepositories]) => {
    if (!isOpen || nextSourceKind !== "repository" || selectedRepositoryPath.value || nextRepositories.length === 0) {
      return;
    }

    selectRepository(nextRepositories[0]);
  },
  { immediate: true },
);

watch(sourceKind, (nextSourceKind) => {
  if (nextSourceKind !== "repository") {
    isRepositoryListOpen.value = false;
    syncDirectoryBrowser();
    return;
  }

  isDirectoryPickerOpen.value = false;
});

watch(repositoryQuery, (value) => {
  if (selectedRepository.value && value === selectedRepository.value.path) {
    return;
  }

  selectedRepositoryPath.value = null;
});
</script>

<template>
  <Dialog
    :open="open"
    @update:open="handleOpenChange"
  >
    <DialogContent
      class="sm:max-w-2xl"
      data-testid="new-session-dialog"
      @interact-outside="handleDialogInteractOutside"
    >
      <DialogHeader>
        <DialogTitle>New Session</DialogTitle>
        <DialogDescription>
          Start a session from a repository or local directory.
        </DialogDescription>
      </DialogHeader>

      <form
        class="space-y-5"
        @submit.prevent="handleSubmit"
      >
        <fieldset
          class="space-y-3"
          aria-label="Source"
        >
          <legend class="text-sm font-medium text-foreground">
            Source
          </legend>

          <div class="grid gap-3 sm:grid-cols-2">
            <label
              for="session-source-repository"
              class="flex cursor-pointer items-start gap-3 rounded-lg border border-border bg-muted/20 p-3 text-sm transition-colors hover:bg-muted/40"
            >
              <input
                id="session-source-repository"
                v-model="sourceKind"
                type="radio"
                value="repository"
                title="Repository"
                aria-describedby="session-source-repository-description"
                class="mt-0.5"
              >
              <div class="space-y-1">
                <span
                  id="source-label-repository"
                  class="block font-medium text-foreground"
                >Repository</span>
                <p
                  id="session-source-repository-description"
                  class="text-muted-foreground"
                >
                  Choose a scanned repository and optional branch strategy.
                </p>
              </div>
            </label>

            <label
              v-if="!isCloudMode"
              for="session-source-directory"
              class="flex cursor-pointer items-start gap-3 rounded-lg border border-border bg-muted/20 p-3 text-sm transition-colors hover:bg-muted/40"
            >
              <input
                id="session-source-directory"
                v-model="sourceKind"
                type="radio"
                value="directory"
                title="Directory"
                aria-describedby="session-source-directory-description"
                class="mt-0.5"
              >
              <div class="space-y-1">
                <span
                  id="source-label-directory"
                  class="block font-medium text-foreground"
                >Directory</span>
                <p
                  id="session-source-directory-description"
                  class="text-muted-foreground"
                >
                  Use an existing local directory as the workspace.
                </p>
              </div>
            </label>
          </div>
        </fieldset>

        <div
          v-if="sourceKind === 'repository'"
          class="grid gap-5 md:grid-cols-2"
        >
          <div class="space-y-2 md:col-span-2">
            <label
              for="new-session-repository"
              class="text-sm font-medium text-foreground"
            >Repository</label>

            <div class="relative">
              <Input
                id="new-session-repository"
                v-model="repositoryQuery"
                autocomplete="off"
                placeholder="Search repositories"
                :disabled="isCreating || isRepositoriesLoading"
                @focus="isRepositoryListOpen = true"
                @blur="handleRepositoryBlur"
              />

              <LoaderCircle
                v-if="isRepositoriesLoading"
                class="absolute top-1/2 right-3 h-4 w-4 -translate-y-1/2 animate-spin text-muted-foreground"
              />

              <div
                v-if="isRepositoryListOpen && !isRepositoriesLoading"
                class="absolute z-50 mt-2 max-h-64 w-full overflow-auto rounded-md border border-border bg-popover p-1 shadow-md"
              >
                <button
                  v-for="repository in filteredRepositories"
                  :key="repository.path"
                  type="button"
                  class="flex w-full items-start justify-between gap-3 rounded-sm px-3 py-2 text-left text-sm hover:bg-accent hover:text-accent-foreground"
                  @mousedown.prevent="selectRepository(repository)"
                >
                  <span class="min-w-0 flex-1">
                    <span class="block truncate font-medium">{{ repository.name }}</span>
                    <span class="block truncate text-xs text-muted-foreground">{{ repository.path }}</span>
                  </span>

                  <Check
                    v-if="selectedRepositoryPath === repository.path"
                    class="mt-0.5 h-4 w-4 shrink-0 text-primary"
                  />
                </button>

                <p
                  v-if="filteredRepositories.length === 0"
                  class="px-3 py-2 text-sm text-muted-foreground"
                >
                  No repositories match your search.
                </p>
              </div>
            </div>
          </div>

          <div class="space-y-2">
            <label
              for="new-session-isolation"
              class="text-sm font-medium text-foreground"
            >Isolation Strategy</label>

            <Select
              v-model="isolationStrategy"
              :disabled="isCreating"
            >
              <SelectTrigger
                id="new-session-isolation"
                class="w-full"
              >
                <SelectValue placeholder="Select a strategy" />
              </SelectTrigger>

              <SelectContent>
                <SelectItem value="worktree">
                  Worktree
                </SelectItem>
                <SelectItem value="clone">
                  Clone
                </SelectItem>
                <SelectItem value="existing">
                  Existing
                </SelectItem>
              </SelectContent>
            </Select>
          </div>

          <div
            v-if="isolationStrategy === 'worktree'"
            class="space-y-2"
          >
            <label
              for="new-session-branch"
              class="text-sm font-medium text-foreground"
            >Branch</label>
            <Input
              id="new-session-branch"
              :model-value="effectiveBranch"
              placeholder="feature/my-session"
              :disabled="isCreating"
              @update:model-value="(value) => {
                branch = String(value);
                branchManuallyEdited = true;
              }"
            />
            <p class="text-xs text-muted-foreground">
              Generated from the title until you edit it manually.
            </p>
          </div>
        </div>

        <div
          v-else
          class="space-y-2"
        >
          <label
            for="new-session-directory"
            class="text-sm font-medium text-foreground"
          >Directory</label>

          <div class="flex gap-2">
            <Input
              id="new-session-directory"
              v-model="directory"
              placeholder="/absolute/path/to/workspace"
              :disabled="isCreating"
            />

            <Popover v-model:open="isDirectoryPickerOpen">
              <PopoverTrigger as-child>
                <Button
                  type="button"
                  variant="outline"
                  :disabled="isCreating"
                  @click="openDirectoryPicker"
                >
                  <Folder class="h-4 w-4" />
                  Browse
                </Button>
              </PopoverTrigger>

              <PopoverContent
                align="end"
                class="w-[32rem] p-0"
                :style="{ backgroundColor: 'var(--card-bg)', opacity: '1' }"
              >
                <div class="border-b border-border bg-card-bg p-3">
                  <div class="flex items-start justify-between gap-3">
                    <div class="min-w-0">
                      <p class="text-xs font-medium uppercase tracking-wide text-muted-foreground">
                        Directory picker
                      </p>
                      <p class="truncate font-mono text-xs text-foreground">
                        {{ directoryPickerLocation }}
                      </p>
                    </div>

                    <div class="flex items-center gap-1">
                      <Button
                        type="button"
                        variant="ghost"
                        size="icon-sm"
                        :disabled="isDirectoryBrowserLoading || !directoryParentPath"
                        @click="goUpDirectory"
                      >
                        <ArrowUp class="h-4 w-4" />
                      </Button>

                      <Button
                        type="button"
                        variant="ghost"
                        size="icon-sm"
                        :disabled="isDirectoryBrowserLoading"
                        @click="refreshDirectoryBrowser"
                      >
                        <RefreshCw :class="['h-4 w-4', isDirectoryBrowserLoading ? 'animate-spin' : '']" />
                      </Button>
                    </div>
                  </div>

                  <Input
                    class="mt-3"
                    :model-value="directorySearch"
                    placeholder="Search directories"
                    :disabled="isDirectoryBrowserLoading"
                    @update:model-value="handleDirectorySearchUpdate"
                  />

                  <div
                    v-if="directoryRoots.length > 1"
                    class="mt-3 flex flex-wrap gap-2"
                  >
                    <Button
                      v-for="root in directoryRoots"
                      :key="root"
                      type="button"
                      variant="outline"
                      size="sm"
                      class="max-w-full"
                      @click="browseDirectory(root)"
                    >
                      <span class="truncate font-mono text-xs">{{ root }}</span>
                    </Button>
                  </div>
                </div>

                <div class="max-h-72 overflow-y-auto bg-card-bg p-2">
                  <button
                    v-for="entry in directoryEntries"
                    :key="entry.path"
                    type="button"
                    class="flex w-full items-start justify-between gap-3 rounded-sm px-3 py-2 text-left text-sm hover:bg-accent hover:text-accent-foreground"
                    @click="handleDirectorySelected(entry.path)"
                  >
                    <span class="min-w-0 flex-1">
                      <span class="flex items-center gap-2 font-medium">
                        <FolderGit2
                          v-if="entry.isGitRepo"
                          class="h-4 w-4 shrink-0"
                        />
                        <Folder
                          v-else
                          class="h-4 w-4 shrink-0"
                        />
                        <span class="truncate">{{ entry.name }}</span>
                      </span>
                      <span class="mt-1 block truncate font-mono text-xs text-muted-foreground">{{ entry.path }}</span>
                    </span>

                    <Check
                      v-if="directory.trim() === entry.path"
                      class="mt-0.5 h-4 w-4 shrink-0 text-primary"
                    />
                  </button>

                  <div
                    v-if="isDirectoryBrowserLoading"
                    class="flex items-center gap-2 px-3 py-6 text-sm text-muted-foreground"
                  >
                    <LoaderCircle class="h-4 w-4 animate-spin" />
                    <span>Loading directories…</span>
                  </div>

                  <p
                    v-else-if="directoryEntries.length === 0"
                    class="px-3 py-6 text-sm text-muted-foreground"
                  >
                    No directories found.
                  </p>
                </div>
              </PopoverContent>
            </Popover>
          </div>

          <p class="text-xs text-muted-foreground">
            Type a path manually or browse from your configured workspace directory.
          </p>
        </div>

        <div class="grid gap-5 md:grid-cols-2">
          <div class="space-y-2">
            <label
              for="session-title"
              class="text-sm font-medium text-foreground"
            >Title</label>
            <Input
              id="session-title"
              v-model="title"
              placeholder="What are you working on?"
              :disabled="isCreating"
            />
            <p class="text-xs text-muted-foreground">
              Optional session name.
            </p>
          </div>

          <div
            v-if="showProjectSelect"
            class="space-y-2"
          >
            <label
              for="new-session-project"
              class="text-sm font-medium text-foreground"
            >Project</label>

            <Select
              v-model="selectedProjectId"
              :disabled="isCreating"
            >
              <SelectTrigger
                id="new-session-project"
                class="w-full"
              >
                <SelectValue placeholder="Ungrouped" />
              </SelectTrigger>

              <SelectContent>
                <SelectItem :value="UNGROUPED_PROJECT_ID">
                  Ungrouped
                </SelectItem>
                <SelectItem
                  v-for="project in userProjects"
                  :key="project.id"
                  :value="project.id"
                >
                  {{ project.name }}
                </SelectItem>
              </SelectContent>
            </Select>
          </div>

          <div
            v-if="showHarnessSelect"
            class="space-y-2"
          >
            <label
              for="new-session-harness"
              class="text-sm font-medium text-foreground"
            >Harness</label>

            <Select
              v-model="selectedHarnessType"
              :disabled="isCreating"
            >
              <SelectTrigger
                id="new-session-harness"
                class="w-full"
              >
                <SelectValue placeholder="Select a harness" />
              </SelectTrigger>

              <SelectContent>
                <SelectItem
                  v-for="harness in availableHarnesses"
                  :key="harness.type"
                  :value="harness.type"
                >
                  {{ harness.displayName }}
                </SelectItem>
              </SelectContent>
            </Select>
          </div>
        </div>

        <div
          v-if="dialogError"
          data-testid="new-session-error"
          class="flex items-start gap-3 rounded-md border border-destructive/30 bg-destructive/10 px-4 py-3 text-sm text-destructive"
          role="alert"
        >
          <AlertCircle class="mt-0.5 h-4 w-4 shrink-0" />
          <p>{{ dialogError }}</p>
        </div>

        <DialogFooter>
          <Button
            type="button"
            variant="outline"
            :disabled="isCreating"
            @click="open = false"
          >
            Cancel
          </Button>

          <Button
            type="submit"
            data-testid="create-session-submit"
            :disabled="!canSubmit"
          >
            <LoaderCircle
              v-if="isCreating"
              class="h-4 w-4 animate-spin"
            />
            {{ isCreating ? "Spawning…" : "Create Session" }}
          </Button>
        </DialogFooter>
      </form>
    </DialogContent>
  </Dialog>
</template>
