// client/src/plugins/builtin/github/components/filters/MilestoneFilter.vue
<script setup lang="ts">
import { ref } from "vue";
import { Milestone, Check, Loader2 } from "lucide-vue-next";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";
import { Command, CommandEmpty, CommandGroup, CommandInput, CommandItem, CommandList } from "@/components/ui/command";
import { Button } from "@/components/ui/button";
import type { GitHubMilestone } from "../../composables/github-types";

const props = defineProps<{
  milestones: GitHubMilestone[];
  isLoading: boolean;
  selected: string | null;
}>();

const emit = defineEmits<{
  select: [milestone: string | null];
}>();

const open = ref(false);

function handleSelect(title: string) {
  emit("select", props.selected === title ? null : title);
  open.value = false;
}
</script>

<template>
  <Popover v-model:open="open">
    <PopoverTrigger as-child>
      <Button variant="filter" size="sm">
        <Milestone :size="12" />
        <span>Milestone</span>
        <span
          v-if="selected"
          class="filter-badge"
        >1</span>
      </Button>
    </PopoverTrigger>
    <PopoverContent
      class="filter-popover-content"
      align="start"
    >
      <Command>
        <CommandInput placeholder="Filter milestones…" />
        <CommandList class="filter-list">
          <div
            v-if="isLoading && milestones.length === 0"
            class="filter-loading"
          >
            <Loader2
              :size="14"
              class="animate-spin"
            />
          </div>
          <CommandEmpty v-else-if="!isLoading && milestones.length === 0">
            No milestones found.
          </CommandEmpty>
          <CommandGroup>
            <CommandItem
              v-if="selected"
              value="__clear__"
              @select="() => { emit('select', null); open = false; }"
            >
              <span class="filter-clear-text">Clear selection</span>
            </CommandItem>
            <CommandItem
              value="__none__"
              @select="() => handleSelect('none')"
            >
              <div class="filter-item">
                <Check
                  :size="13"
                  :style="{ opacity: selected === 'none' ? 1 : 0 }"
                  class="filter-check"
                />
                <span class="filter-item-text">No milestone</span>
              </div>
            </CommandItem>
            <CommandItem
              v-for="ms in milestones"
              :key="ms.number"
              :value="ms.title"
              @select="() => handleSelect(ms.title)"
            >
              <div class="filter-item">
                <Check
                  :size="13"
                  :style="{ opacity: selected === ms.title ? 1 : 0 }"
                  class="filter-check"
                />
                <div class="milestone-info">
                  <span class="filter-item-text">{{ ms.title }}</span>
                  <span class="milestone-meta">{{ ms.open_issues }} open · {{ ms.closed_issues }} closed</span>
                </div>
              </div>
            </CommandItem>
          </CommandGroup>
        </CommandList>
      </Command>
    </PopoverContent>
  </Popover>
</template>

<style scoped>
.filter-badge {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  min-width: 16px;
  height: 16px;
  padding: 0 4px;
  border-radius: 0;
  background: var(--accent-muted, rgba(99, 102, 241, 0.2));
  color: var(--accent);
  font-size: 10px;
  font-weight: 600;
}

.filter-popover-content {
  width: 224px;
  padding: 0;
}

.filter-list {
  max-height: 224px;
}

.filter-loading {
  display: flex;
  justify-content: center;
  padding: 12px;
  color: var(--muted);
}

.filter-clear-text {
  font-size: 13px;
  color: var(--muted);
}

.filter-item {
  display: flex;
  align-items: center;
  gap: 8px;
  flex: 1;
  min-width: 0;
}

.filter-check {
  flex-shrink: 0;
}

.milestone-info {
  display: flex;
  flex-direction: column;
  min-width: 0;
}

.filter-item-text {
  font-size: 13px;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.milestone-meta {
  font-size: 10px;
  color: var(--muted);
}
</style>

// client/src/integrations/github/components/filters/milestone-filter.tsx

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/ui/popover";
import {
  Command,
  CommandEmpty,
  CommandGroup,
  CommandInput,
  CommandItem,
  CommandList,
} from "@/components/ui/command";
import { Check, Milestone, Loader2 } from "lucide-react";
import { cn } from "@/lib/utils";
import type { GitHubMilestone } from "../../types";

interface MilestoneFilterProps {
  milestones: GitHubMilestone[];
  isLoading: boolean;
  selected: string | null;
  onSelect: (milestone: string | null) => void;
}

export function MilestoneFilter({
  milestones,
  isLoading,
  selected,
  onSelect,
}: MilestoneFilterProps) {
  const [open, setOpen] = useState(false);

  return (
    <Popover open={open} onOpenChange={setOpen}>
      <PopoverTrigger asChild>
        <Button variant="ghost" size="sm" className="gap-1.5 h-7 text-xs">
          <Milestone className="h-3 w-3" />
          Milestone
          {selected && (
            <Badge variant="secondary" className="text-[10px] ml-0.5 px-1 py-0">
              1
            </Badge>
          )}
        </Button>
      </PopoverTrigger>
      <PopoverContent className="w-56 p-0" align="start">
        <Command>
          <CommandInput placeholder="Filter milestones…" />
          <CommandList className="thin-scrollbar max-h-56">
            {isLoading && milestones.length === 0 && (
              <div className="flex justify-center py-3">
                <Loader2 className="h-3.5 w-3.5 animate-spin text-muted-foreground" />
              </div>
            )}
            {!isLoading && milestones.length === 0 && (
              <CommandEmpty>No milestones found.</CommandEmpty>
            )}
            <CommandGroup>
              {/* Clear / special options */}
              {selected && (
                <CommandItem
                  value="__clear__"
                  onSelect={() => {
                    onSelect(null);
                    setOpen(false);
                  }}
                >
                  <span className="text-sm text-muted-foreground">Clear selection</span>
                </CommandItem>
              )}
              <CommandItem
                value="__none__"
                onSelect={() => {
                  onSelect(selected === "none" ? null : "none");
                  setOpen(false);
                }}
              >
                <div className="flex items-center gap-2">
                  <Check
                    className={cn(
                      "h-3.5 w-3.5 shrink-0",
                      selected === "none" ? "opacity-100" : "opacity-0"
                    )}
                  />
                  <span className="text-sm">No milestone</span>
                </div>
              </CommandItem>

              {milestones.map((ms) => {
                const isSelected = selected === ms.title;
                return (
                  <CommandItem
                    key={ms.number}
                    value={ms.title}
                    onSelect={() => {
                      onSelect(isSelected ? null : ms.title);
                      setOpen(false);
                    }}
                  >
                    <div className="flex items-center gap-2 flex-1 min-w-0">
                      <Check
                        className={cn(
                          "h-3.5 w-3.5 shrink-0",
                          isSelected ? "opacity-100" : "opacity-0"
                        )}
                      />
                      <div className="flex flex-col min-w-0">
                        <span className="text-sm truncate">{ms.title}</span>
                        <span className="text-[10px] text-muted-foreground">
                          {ms.open_issues} open · {ms.closed_issues} closed
                        </span>
                      </div>
                    </div>
                  </CommandItem>
                );
              })}
            </CommandGroup>
          </CommandList>
        </Command>
      </PopoverContent>
    </Popover>
  );
}
