// client/src/integrations/github/components/issue-filter-bar.tsx

import { useCallback } from "react";
import { Button } from "@/components/ui/button";
import { CircleDot, CircleCheck } from "lucide-react";
import { FilterExpressionField } from "./filter-expression-field";
import { LabelFilter } from "./filters/label-filter";
import { AuthorFilter } from "./filters/author-filter";
import { MilestoneFilter } from "./filters/milestone-filter";
import { AssigneeFilter } from "./filters/assignee-filter";
import { SortControl } from "./filters/sort-control";
import type { IssueFilterState, GitHubLabel, GitHubMilestone, GitHubAssignee } from "../types";

interface IssueFilterBarProps {
  filter: IssueFilterState;
  onChange: (filter: IssueFilterState) => void;
  isSearching?: boolean;
  labels: GitHubLabel[];
  labelsLoading: boolean;
  milestones: GitHubMilestone[];
  milestonesLoading: boolean;
  assignees: GitHubAssignee[];
  assigneesLoading: boolean;
}

export function IssueFilterBar({
  filter,
  onChange,
  isSearching,
  labels,
  labelsLoading,
  milestones,
  milestonesLoading,
  assignees,
  assigneesLoading,
}: IssueFilterBarProps) {
  const setFilter = useCallback(
    (partial: Partial<IssueFilterState>) => {
      onChange({ ...filter, ...partial });
    },
    [filter, onChange]
  );

  const handleLabelToggle = useCallback(
    (label: string) => {
      const next = filter.labels.includes(label)
        ? filter.labels.filter((l) => l !== label)
        : [...filter.labels, label];
      setFilter({ labels: next });
    },
    [filter.labels, setFilter]
  );

  const handleSortChange = useCallback(
    (sort: "created" | "updated" | "comments", direction: "asc" | "desc") => {
      setFilter({ sort, direction });
    },
    [setFilter]
  );

  return (
    <div className="space-y-2">
      {/* Expression field — full width */}
      <FilterExpressionField
        filter={filter}
        onChange={onChange}
        isSearching={isSearching}
      />

      {/* Filter controls row */}
      <div className="flex items-center gap-1 flex-wrap">
        {/* State toggle */}
        <Button
          variant={filter.state === "open" ? "default" : "ghost"}
          size="sm"
          className="gap-1 h-7 text-xs"
          onClick={() => setFilter({ state: "open" })}
        >
          <CircleDot className="h-3 w-3" />
          Open
        </Button>
        <Button
          variant={filter.state === "closed" ? "default" : "ghost"}
          size="sm"
          className="gap-1 h-7 text-xs"
          onClick={() => setFilter({ state: "closed" })}
        >
          <CircleCheck className="h-3 w-3" />
          Closed
        </Button>

        {/* Separator */}
        <div className="h-4 w-px bg-border mx-1" />

        {/* Filter dropdowns */}
        <LabelFilter
          labels={labels}
          isLoading={labelsLoading}
          selected={filter.labels}
          onToggle={handleLabelToggle}
        />
        <AuthorFilter
          users={assignees}
          isLoading={assigneesLoading}
          selected={filter.author}
          onSelect={(author) => setFilter({ author })}
        />
        <MilestoneFilter
          milestones={milestones}
          isLoading={milestonesLoading}
          selected={filter.milestone}
          onSelect={(milestone) => setFilter({ milestone })}
        />
        <AssigneeFilter
          assignees={assignees}
          isLoading={assigneesLoading}
          selected={filter.assignee}
          onSelect={(assignee) => setFilter({ assignee })}
        />

        {/* Sort — push to right */}
        <div className="ml-auto">
          <SortControl
            sort={filter.sort}
            direction={filter.direction}
            onChange={handleSortChange}
          />
        </div>
      </div>
    </div>
  );
}

// client/src/plugins/builtin/github/components/IssueFilterBar.vue
<script setup lang="ts">
import { CircleDot, CircleCheck } from "lucide-vue-next";
import FilterExpressionField from "./FilterExpressionField.vue";
import LabelFilter from "./filters/LabelFilter.vue";
import AuthorFilter from "./filters/AuthorFilter.vue";
import MilestoneFilter from "./filters/MilestoneFilter.vue";
import AssigneeFilter from "./filters/AssigneeFilter.vue";
import SortControl from "./filters/SortControl.vue";
import { Button } from "@/components/ui/button";
import type { IssueFilterState, GitHubLabel, GitHubMilestone, GitHubAssignee } from "../composables/github-types";

const props = defineProps<{
  filter: IssueFilterState;
  isSearching?: boolean;
  labels: GitHubLabel[];
  labelsLoading: boolean;
  milestones: GitHubMilestone[];
  milestonesLoading: boolean;
  assignees: GitHubAssignee[];
  assigneesLoading: boolean;
}>();

const emit = defineEmits<{
  change: [filter: IssueFilterState];
}>();

function setFilter(partial: Partial<IssueFilterState>) {
  emit("change", { ...props.filter, ...partial });
}

function handleLabelToggle(label: string) {
  const next = props.filter.labels.includes(label)
    ? props.filter.labels.filter((l) => l !== label)
    : [...props.filter.labels, label];
  setFilter({ labels: next });
}

function handleSortChange(sort: "created" | "updated" | "comments", direction: "asc" | "desc") {
  setFilter({ sort, direction });
}
</script>

<template>
  <div class="filter-bar">
    <!-- Expression field — full width -->
    <FilterExpressionField
      :filter="filter"
      :is-searching="isSearching"
      @change="(f) => emit('change', f)"
    />

    <!-- Filter controls row -->
    <div class="filter-controls">
      <!-- State toggle -->
      <Button
        variant="filter"
        size="sm"
        :data-active="filter.state === 'open'"
        @click="setFilter({ state: 'open' })"
      >
        <CircleDot :size="12" />
        <span>Open</span>
      </Button>
      <Button
        variant="filter"
        size="sm"
        :data-active="filter.state === 'closed'"
        @click="setFilter({ state: 'closed' })"
      >
        <CircleCheck :size="12" />
        <span>Closed</span>
      </Button>

      <!-- Separator -->
      <div class="filter-separator" />

      <!-- Filter dropdowns -->
      <LabelFilter
        :labels="labels"
        :is-loading="labelsLoading"
        :selected="filter.labels"
        @toggle="handleLabelToggle"
      />
      <AuthorFilter
        :users="assignees"
        :is-loading="assigneesLoading"
        :selected="filter.author"
        @select="(v) => setFilter({ author: v })"
      />
      <MilestoneFilter
        :milestones="milestones"
        :is-loading="milestonesLoading"
        :selected="filter.milestone"
        @select="(v) => setFilter({ milestone: v })"
      />
      <AssigneeFilter
        :assignees="assignees"
        :is-loading="assigneesLoading"
        :selected="filter.assignee"
        @select="(v) => setFilter({ assignee: v })"
      />

      <!-- Sort — pushed to right -->
      <div class="filter-sort">
        <SortControl
          :sort="filter.sort"
          :direction="filter.direction"
          @change="handleSortChange"
        />
      </div>
    </div>
  </div>
</template>

<style scoped>
.filter-bar {
  display: flex;
  flex-direction: column;
  gap: 8px;
  padding: 10px 0 4px;
}

.filter-controls {
  display: flex;
  align-items: center;
  gap: 2px;
  flex-wrap: wrap;
}

.filter-separator {
  width: 1px;
  height: 16px;
  background: var(--border);
  margin: 0 4px;
}

.filter-sort {
  margin-left: auto;
}
</style>
