// client/src/components/analytics/models-tab.tsx
"use client";

import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
} from "recharts";
import type { ModelAnalytics } from "@/lib/api-types";
import { formatLargeNumber, formatAnalyticsCost } from "@/lib/format-utils";
import { CHART_COLORS } from "@/lib/chart-theme";

interface ModelsTabProps {
  models: ModelAnalytics[];
  isLoading: boolean;
}

export function ModelsTab({ models, isLoading }: ModelsTabProps) {
  if (!isLoading && models.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center py-16 text-center text-muted-foreground">
        <p className="text-sm">No model data yet.</p>
        <p className="text-xs mt-1">Model analytics will appear once sessions use AI models.</p>
      </div>
    );
  }

  // Sort by cost descending for chart
  const sorted = [...models].sort((a, b) => b.cost - a.cost);

  const chartData = sorted.map((m) => ({
    name: m.modelId.split("/").pop() ?? m.modelId,
    cost: m.cost,
    tokens: m.tokens,
  }));

  return (
    <div className="space-y-4 sm:space-y-6">
      {/* Horizontal bar chart */}
      {chartData.length > 0 && (
        <div className="rounded-lg border border-border bg-card p-4">
          <h3 className="text-sm font-semibold mb-3">Cost by Model</h3>
          <div className="h-48">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart
                data={chartData}
                layout="vertical"
                margin={{ top: 0, right: 60, left: 0, bottom: 0 }}
              >
                <CartesianGrid strokeDasharray="3 3" stroke="currentColor" strokeOpacity={0.08} horizontal={false} />
                <XAxis
                  type="number"
                  tick={{ fontSize: 11, fill: "currentColor", opacity: 0.5 }}
                  tickLine={false}
                  axisLine={false}
                  tickFormatter={(v: number) => `$${v.toFixed(2)}`}
                />
                <YAxis
                  type="category"
                  dataKey="name"
                  tick={{ fontSize: 11, fill: "currentColor", opacity: 0.7 }}
                  tickLine={false}
                  axisLine={false}
                  width={120}
                />
                <Tooltip
                  contentStyle={{
                    fontSize: 12,
                    borderRadius: 8,
                    border: "1px solid hsl(var(--border))",
                    background: "hsl(var(--popover))",
                    color: "hsl(var(--popover-foreground))",
                  }}
                  formatter={(value) => {
                    const num = typeof value === "number" ? value : 0;
                    return [formatAnalyticsCost(num), "Cost"];
                  }}
                />
                <Bar dataKey="cost" fill={CHART_COLORS[0]} radius={[0, 4, 4, 0]} />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>
      )}

      {/* Detail table */}
      <div className="overflow-x-auto rounded-lg border border-border">
        <table className="w-full text-sm">
          <thead className="border-b border-border bg-muted/30">
            <tr>
              <th className="px-3 py-2 text-left text-xs font-semibold uppercase tracking-wider text-muted-foreground">Model</th>
              <th className="px-3 py-2 text-left text-xs font-semibold uppercase tracking-wider text-muted-foreground hidden sm:table-cell">Provider</th>
              <th className="px-3 py-2 text-right text-xs font-semibold uppercase tracking-wider text-muted-foreground">Tokens</th>
              <th className="px-3 py-2 text-right text-xs font-semibold uppercase tracking-wider text-muted-foreground">Cost</th>
              <th className="px-3 py-2 text-right text-xs font-semibold uppercase tracking-wider text-muted-foreground hidden sm:table-cell">Messages</th>
              <th className="px-3 py-2 text-right text-xs font-semibold uppercase tracking-wider text-muted-foreground hidden sm:table-cell">Avg/Msg</th>
            </tr>
          </thead>
          <tbody>
            {sorted.map((model) => (
              <tr
                key={model.modelId}
                className="border-b border-border last:border-0 hover:bg-muted/20 transition-colors even:bg-muted/10"
              >
                <td className="px-3 py-2 font-medium max-w-[160px]">
                  <span className="truncate block">{model.modelId.split("/").pop() ?? model.modelId}</span>
                </td>
                <td className="px-3 py-2 text-muted-foreground hidden sm:table-cell">
                  {model.providerId}
                </td>
                <td className="px-3 py-2 text-right tabular-nums text-muted-foreground">
                  {formatLargeNumber(model.tokens)}
                </td>
                <td className="px-3 py-2 text-right tabular-nums font-medium">
                  {formatAnalyticsCost(model.cost)}
                </td>
                <td className="px-3 py-2 text-right tabular-nums text-muted-foreground hidden sm:table-cell">
                  {model.messageCount.toLocaleString()}
                </td>
                <td className="px-3 py-2 text-right tabular-nums text-muted-foreground hidden sm:table-cell">
                  {formatAnalyticsCost(model.avgCostPerMessage)}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}

// client/src/components/analytics/tabs/ModelsTab.vue
<script setup lang="ts">
import { computed } from "vue"
import HorizontalCostBars from "@/components/analytics/charts/HorizontalCostBars.vue"
import type { ModelAnalytics } from "@/api/client"
import { formatAnalyticsCost } from "@/lib/format-utils"

interface CostBarItem {
  name: string
  cost: number
  maxCost: number
  detail?: string
}

interface ModelTableRow extends ModelAnalytics {
  key: string
  formattedTokens: string
  formattedCost: string
  formattedEstimatedCost: string
  formattedMessageCount: string
  formattedAverageCostPerMessage: string
}

interface Props {
  models: readonly ModelAnalytics[]
  isLoading: boolean
  error?: string
  chartEmptyMessage?: string
  tableEmptyMessage?: string
}

const props = withDefaults(defineProps<Props>(), {
  error: undefined,
  chartEmptyMessage: "No model cost data available for the selected filters.",
  tableEmptyMessage: "No model analytics available for the selected filters.",
})

const integerFormatter = new Intl.NumberFormat("en-US")

const hasModels = computed(() => props.models.length > 0)

const sortedModels = computed<ModelAnalytics[]>(() => {
  return [...props.models].sort((left, right) => {
    return right.cost - left.cost
      || right.estimatedCost - left.estimatedCost
      || right.tokens - left.tokens
      || left.modelId.localeCompare(right.modelId)
  })
})

const maxCost = computed(() => {
  return sortedModels.value.reduce((highest, model) => Math.max(highest, model.cost), 0)
})

const chartItems = computed<CostBarItem[]>(() => {
  return sortedModels.value.map((model) => ({
    name: model.modelId,
    cost: model.cost,
    maxCost: maxCost.value,
    detail: `${model.providerId} · ${integerFormatter.format(model.messageCount)} messages · Est. ${formatAnalyticsCost(model.estimatedCost)}`,
  }))
})

const tableRows = computed<ModelTableRow[]>(() => {
  return sortedModels.value.map((model) => ({
    ...model,
    key: `${model.providerId}:${model.modelId}`,
    formattedTokens: integerFormatter.format(model.tokens),
    formattedCost: formatAnalyticsCost(model.cost),
    formattedEstimatedCost: formatAnalyticsCost(model.estimatedCost),
    formattedMessageCount: integerFormatter.format(model.messageCount),
    formattedAverageCostPerMessage: formatAnalyticsCost(model.avgCostPerMessage),
  }))
})

const emptyStateMessage = computed(() => {
  return props.error
    ? `Unable to load model analytics (${props.error}).`
    : props.tableEmptyMessage
})
</script>

<template>
  <section
    class="models-tab"
    aria-label="Models analytics"
  >
    <div
      v-if="isLoading"
      class="models-tab__state models-tab__state--loading"
    >
      Loading model analytics…
    </div>

    <div
      v-else-if="!hasModels"
      class="models-tab__state"
    >
      {{ emptyStateMessage }}
    </div>

    <div
      v-else
      class="models-tab__content"
    >
      <section
        class="models-tab__panel"
        aria-label="Cost by model"
      >
        <h2 class="models-tab__title">
          Cost by model
        </h2>
        <HorizontalCostBars
          :items="chartItems"
          :empty-message="chartEmptyMessage"
        />
      </section>

      <section
        class="models-tab__panel models-tab__panel--table"
        aria-label="Model details"
      >
        <h2 class="models-tab__title">
          Model details
        </h2>
        <div class="models-tab__table-shell">
          <table class="models-tab__table">
            <caption class="models-tab__sr-only">
              Model analytics including model, provider, tokens, cost, estimated cost, messages, and average cost per message.
            </caption>
            <thead>
              <tr>
                <th
                  scope="col"
                  class="models-tab__head"
                >
                  Model
                </th>
                <th
                  scope="col"
                  class="models-tab__head"
                >
                  Provider
                </th>
                <th
                  scope="col"
                  class="models-tab__head models-tab__head--right"
                >
                  Tokens
                </th>
                <th
                  scope="col"
                  class="models-tab__head models-tab__head--right"
                >
                  Cost
                </th>
                <th
                  scope="col"
                  class="models-tab__head models-tab__head--right"
                >
                  Estimated cost
                </th>
                <th
                  scope="col"
                  class="models-tab__head models-tab__head--right"
                >
                  Messages
                </th>
                <th
                  scope="col"
                  class="models-tab__head models-tab__head--right"
                >
                  Avg cost/msg
                </th>
              </tr>
            </thead>

            <tbody>
              <tr
                v-for="row in tableRows"
                :key="row.key"
                class="models-tab__row"
              >
                <td class="models-tab__cell">
                  <div class="models-tab__primary">
                    {{ row.modelId }}
                  </div>
                </td>
                <td class="models-tab__cell">
                  <div class="models-tab__secondary models-tab__secondary--strong">
                    {{ row.providerId }}
                  </div>
                </td>
                <td class="models-tab__cell models-tab__cell--right">
                  {{ row.formattedTokens }}
                </td>
                <td class="models-tab__cell models-tab__cell--right">
                  {{ row.formattedCost }}
                </td>
                <td class="models-tab__cell models-tab__cell--right">
                  {{ row.formattedEstimatedCost }}
                </td>
                <td class="models-tab__cell models-tab__cell--right">
                  {{ row.formattedMessageCount }}
                </td>
                <td class="models-tab__cell models-tab__cell--right">
                  {{ row.formattedAverageCostPerMessage }}
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </section>
    </div>
  </section>
</template>

<style scoped>
.models-tab {
  min-width: 0;
}

.models-tab__content {
  display: grid;
  grid-template-columns: minmax(0, 1fr);
  gap: 12px;
}

.models-tab__panel {
  display: flex;
  flex-direction: column;
  gap: 12px;
  min-width: 0;
  padding: 16px;
  border: 1px solid var(--border);
  border-radius: var(--radius-card);
  background: var(--card-bg);
}

.models-tab__panel--table {
  padding: 16px 0 0;
  overflow: hidden;
}

.models-tab__panel--table .models-tab__title {
  padding: 0 16px;
}

.models-tab__title {
  margin: 0;
  color: var(--text);
  font-size: 13px;
  font-weight: 600;
}

.models-tab__state {
  display: flex;
  min-height: 280px;
  align-items: center;
  justify-content: center;
  border: 1px dashed var(--border);
  border-radius: var(--radius-card);
  padding: 24px;
  color: var(--muted);
  font-size: 13px;
  text-align: center;
}

.models-tab__state--loading {
  color: var(--text);
}

.models-tab__table-shell {
  overflow-x: auto;
}

.models-tab__table {
  width: 100%;
  min-width: 720px;
  border-collapse: collapse;
}

.models-tab__head {
  padding: 8px 16px;
  border-bottom: 1px solid var(--border);
  color: var(--muted);
  font-size: 12px;
  font-weight: 500;
  text-align: left;
  white-space: nowrap;
}

.models-tab__head--right {
  text-align: right;
}

.models-tab__row {
  transition: background-color var(--transition);
}

.models-tab__row:hover {
  background: color-mix(in srgb, var(--text) 3%, transparent);
}

.models-tab__row + .models-tab__row {
  border-top: 1px solid var(--border);
}

.models-tab__cell {
  padding: 10px 16px;
  color: var(--text);
  font-size: 13px;
  line-height: 1.5;
  vertical-align: top;
}

.models-tab__cell--right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

.models-tab__primary {
  color: var(--text);
  font-weight: 500;
  overflow-wrap: anywhere;
}

.models-tab__secondary {
  color: var(--muted);
  overflow-wrap: anywhere;
}

.models-tab__secondary--strong {
  color: var(--text);
  font-weight: 500;
}

.models-tab__sr-only {
  position: absolute;
  width: 1px;
  height: 1px;
  padding: 0;
  margin: -1px;
  overflow: hidden;
  clip: rect(0, 0, 0, 0);
  white-space: nowrap;
  border: 0;
}

@media (max-width: 720px) {
  .models-tab__head,
  .models-tab__cell {
    padding-right: 14px;
    padding-left: 14px;
  }
}
</style>
