// client/src/integrations/github/components/filters/assignee-filter.tsx

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/ui/popover";
import {
  Command,
  CommandEmpty,
  CommandGroup,
  CommandInput,
  CommandItem,
  CommandList,
} from "@/components/ui/command";
import { Check, UserCheck, Loader2 } from "lucide-react";
import { cn } from "@/lib/utils";
import type { GitHubAssignee } from "../../types";

interface AssigneeFilterProps {
  assignees: GitHubAssignee[];
  isLoading: boolean;
  selected: string | null;
  onSelect: (assignee: string | null) => void;
}

export function AssigneeFilter({
  assignees,
  isLoading,
  selected,
  onSelect,
}: AssigneeFilterProps) {
  const [open, setOpen] = useState(false);

  return (
    <Popover open={open} onOpenChange={setOpen}>
      <PopoverTrigger asChild>
        <Button variant="ghost" size="sm" className="gap-1.5 h-7 text-xs">
          <UserCheck className="h-3 w-3" />
          Assignee
          {selected && (
            <Badge variant="secondary" className="text-[10px] ml-0.5 px-1 py-0">
              1
            </Badge>
          )}
        </Button>
      </PopoverTrigger>
      <PopoverContent className="w-56 p-0" align="start">
        <Command>
          <CommandInput placeholder="Filter assignees…" />
          <CommandList className="thin-scrollbar max-h-56">
            {isLoading && assignees.length === 0 && (
              <div className="flex justify-center py-3">
                <Loader2 className="h-3.5 w-3.5 animate-spin text-muted-foreground" />
              </div>
            )}
            {!isLoading && assignees.length === 0 && (
              <CommandEmpty>No assignees found.</CommandEmpty>
            )}
            <CommandGroup>
              {/* Clear option */}
              {selected && (
                <CommandItem
                  value="__clear__"
                  onSelect={() => {
                    onSelect(null);
                    setOpen(false);
                  }}
                >
                  <span className="text-sm text-muted-foreground">Clear selection</span>
                </CommandItem>
              )}
              <CommandItem
                value="__none__"
                onSelect={() => {
                  onSelect(selected === "none" ? null : "none");
                  setOpen(false);
                }}
              >
                <div className="flex items-center gap-2">
                  <Check
                    className={cn(
                      "h-3.5 w-3.5 shrink-0",
                      selected === "none" ? "opacity-100" : "opacity-0"
                    )}
                  />
                  <span className="text-sm">Unassigned</span>
                </div>
              </CommandItem>

              {assignees.map((user) => {
                const isSelected = selected === user.login;
                return (
                  <CommandItem
                    key={user.login}
                    value={user.login}
                    onSelect={() => {
                      onSelect(isSelected ? null : user.login);
                      setOpen(false);
                    }}
                  >
                    <div className="flex items-center gap-2 flex-1 min-w-0">
                      <Check
                        className={cn(
                          "h-3.5 w-3.5 shrink-0",
                          isSelected ? "opacity-100" : "opacity-0"
                        )}
                      />
                      <img
                        src={user.avatar_url}
                        alt=""
                        className="h-4 w-4 rounded-full shrink-0"
                      />
                      <span className="text-sm truncate">{user.login}</span>
                    </div>
                  </CommandItem>
                );
              })}
            </CommandGroup>
          </CommandList>
        </Command>
      </PopoverContent>
    </Popover>
  );
}

// client/src/plugins/builtin/github/components/filters/AssigneeFilter.vue
<script setup lang="ts">
import { ref } from "vue";
import { UserCheck, Check, Loader2 } from "lucide-vue-next";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";
import { Command, CommandEmpty, CommandGroup, CommandInput, CommandItem, CommandList } from "@/components/ui/command";
import { Button } from "@/components/ui/button";
import type { GitHubAssignee } from "../../composables/github-types";

const props = defineProps<{
  assignees: GitHubAssignee[];
  isLoading: boolean;
  selected: string | null;
}>();

const emit = defineEmits<{
  select: [assignee: string | null];
}>();

const open = ref(false);

function handleSelect(login: string) {
  emit("select", props.selected === login ? null : login);
  open.value = false;
}
</script>

<template>
  <Popover v-model:open="open">
    <PopoverTrigger as-child>
      <Button variant="filter" size="sm">
        <UserCheck :size="12" />
        <span>Assignee</span>
        <span
          v-if="selected"
          class="filter-badge"
        >1</span>
      </Button>
    </PopoverTrigger>
    <PopoverContent
      class="filter-popover-content"
      align="start"
    >
      <Command>
        <CommandInput placeholder="Filter assignees…" />
        <CommandList class="filter-list">
          <div
            v-if="isLoading && assignees.length === 0"
            class="filter-loading"
          >
            <Loader2
              :size="14"
              class="animate-spin"
            />
          </div>
          <CommandEmpty v-else-if="!isLoading && assignees.length === 0">
            No assignees found.
          </CommandEmpty>
          <CommandGroup>
            <CommandItem
              v-if="selected"
              value="__clear__"
              @select="() => { emit('select', null); open = false; }"
            >
              <span class="filter-clear-text">Clear selection</span>
            </CommandItem>
            <CommandItem
              value="__none__"
              @select="() => handleSelect('none')"
            >
              <div class="filter-item">
                <Check
                  :size="13"
                  :style="{ opacity: selected === 'none' ? 1 : 0 }"
                  class="filter-check"
                />
                <span class="filter-item-text">Unassigned</span>
              </div>
            </CommandItem>
            <CommandItem
              v-for="user in assignees"
              :key="user.login"
              :value="user.login"
              @select="() => handleSelect(user.login)"
            >
              <div class="filter-item">
                <Check
                  :size="13"
                  :style="{ opacity: selected === user.login ? 1 : 0 }"
                  class="filter-check"
                />
                <img
                  :src="user.avatar_url"
                  alt=""
                  class="user-avatar"
                >
                <span class="filter-item-text">{{ user.login }}</span>
              </div>
            </CommandItem>
          </CommandGroup>
        </CommandList>
      </Command>
    </PopoverContent>
  </Popover>
</template>

<style scoped>
.filter-badge {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  min-width: 16px;
  height: 16px;
  padding: 0 4px;
  border-radius: 0;
  background: var(--accent-muted, rgba(99, 102, 241, 0.2));
  color: var(--accent);
  font-size: 10px;
  font-weight: 600;
}

.filter-popover-content {
  width: 224px;
  padding: 0;
}

.filter-list {
  max-height: 224px;
}

.filter-loading {
  display: flex;
  justify-content: center;
  padding: 12px;
  color: var(--muted);
}

.filter-clear-text {
  font-size: 13px;
  color: var(--muted);
}

.filter-item {
  display: flex;
  align-items: center;
  gap: 8px;
  flex: 1;
  min-width: 0;
}

.filter-check {
  flex-shrink: 0;
}

.user-avatar {
  width: 16px;
  height: 16px;
  border-radius: 50%;
  object-fit: cover;
  flex-shrink: 0;
}

.filter-item-text {
  font-size: 13px;
  min-width: 0;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
</style>
