// client/src/integrations/github/components/filters/label-filter.tsx

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/ui/popover";
import {
  Command,
  CommandEmpty,
  CommandGroup,
  CommandInput,
  CommandItem,
  CommandList,
} from "@/components/ui/command";
import { Check, Tag, Loader2 } from "lucide-react";
import { cn } from "@/lib/utils";
import type { GitHubLabel } from "../../types";

interface LabelFilterProps {
  labels: GitHubLabel[];
  isLoading: boolean;
  selected: string[];
  onToggle: (label: string) => void;
}

export function LabelFilter({
  labels,
  isLoading,
  selected,
  onToggle,
}: LabelFilterProps) {
  const [open, setOpen] = useState(false);

  return (
    <Popover open={open} onOpenChange={setOpen}>
      <PopoverTrigger asChild>
        <Button variant="ghost" size="sm" className="gap-1.5 h-7 text-xs">
          <Tag className="h-3 w-3" />
          Label
          {selected.length > 0 && (
            <Badge variant="secondary" className="text-[10px] ml-0.5 px-1 py-0">
              {selected.length}
            </Badge>
          )}
        </Button>
      </PopoverTrigger>
      <PopoverContent className="w-64 p-0" align="start">
        <Command>
          <CommandInput placeholder="Filter labels…" />
          <CommandList className="thin-scrollbar max-h-56">
            {isLoading && labels.length === 0 && (
              <div className="flex justify-center py-3">
                <Loader2 className="h-3.5 w-3.5 animate-spin text-muted-foreground" />
              </div>
            )}
            {!isLoading && labels.length === 0 && (
              <CommandEmpty>No labels found.</CommandEmpty>
            )}
            <CommandGroup>
              {labels.map((label) => {
                const isSelected = selected.includes(label.name);
                return (
                  <CommandItem
                    key={label.name}
                    value={label.name}
                    onSelect={() => onToggle(label.name)}
                  >
                    <div className="flex items-center gap-2 flex-1 min-w-0">
                      <div
                        className={cn(
                          "flex h-4 w-4 shrink-0 items-center justify-center rounded-sm border",
                          isSelected
                            ? "border-primary bg-primary text-primary-foreground"
                            : "border-muted-foreground/30"
                        )}
                      >
                        {isSelected && <Check className="h-3 w-3" />}
                      </div>
                      <span
                        className="h-2.5 w-2.5 rounded-full shrink-0"
                        style={{ backgroundColor: `#${label.color}` }}
                      />
                      <span className="text-sm truncate">{label.name}</span>
                    </div>
                  </CommandItem>
                );
              })}
            </CommandGroup>
          </CommandList>
        </Command>
      </PopoverContent>
    </Popover>
  );
}

// client/src/plugins/builtin/github/components/filters/LabelFilter.vue
<script setup lang="ts">
import { ref } from "vue";
import { Tag, Check, Loader2 } from "lucide-vue-next";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";
import { Command, CommandEmpty, CommandGroup, CommandInput, CommandItem, CommandList } from "@/components/ui/command";
import { Button } from "@/components/ui/button";
import type { GitHubLabel } from "../../composables/github-types";

defineProps<{
  labels: GitHubLabel[];
  isLoading: boolean;
  selected: string[];
}>();

const emit = defineEmits<{
  toggle: [label: string];
}>();

const open = ref(false);
</script>

<template>
  <Popover v-model:open="open">
    <PopoverTrigger as-child>
      <Button variant="filter" size="sm">
        <Tag :size="12" />
        <span>Label</span>
        <span
          v-if="selected.length > 0"
          class="filter-badge"
        >{{ selected.length }}</span>
      </Button>
    </PopoverTrigger>
    <PopoverContent
      class="filter-popover-content"
      align="start"
    >
      <Command>
        <CommandInput placeholder="Filter labels…" />
        <CommandList class="filter-list">
          <div
            v-if="isLoading && labels.length === 0"
            class="filter-loading"
          >
            <Loader2
              :size="14"
              class="animate-spin"
            />
          </div>
          <CommandEmpty v-else-if="!isLoading && labels.length === 0">
            No labels found.
          </CommandEmpty>
          <CommandGroup>
            <CommandItem
              v-for="label in labels"
              :key="label.name"
              :value="label.name"
              @select="() => emit('toggle', label.name)"
            >
              <div class="filter-item">
                <div :class="['filter-checkbox', selected.includes(label.name) && 'filter-checkbox--checked']">
                  <Check
                    v-if="selected.includes(label.name)"
                    :size="10"
                  />
                </div>
                <span
                  class="label-dot"
                  :style="{ backgroundColor: `#${label.color}` }"
                />
                <span class="filter-item-text">{{ label.name }}</span>
              </div>
            </CommandItem>
          </CommandGroup>
        </CommandList>
      </Command>
    </PopoverContent>
  </Popover>
</template>

<style scoped>
.filter-badge {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  min-width: 16px;
  height: 16px;
  padding: 0 4px;
  border-radius: 0;
  background: var(--accent-muted, rgba(99, 102, 241, 0.2));
  color: var(--accent);
  font-size: 10px;
  font-weight: 600;
}

.filter-popover-content {
  width: 256px;
  padding: 0;
}

.filter-list {
  max-height: 224px;
}

.filter-loading {
  display: flex;
  justify-content: center;
  padding: 12px;
  color: var(--muted);
}

.filter-item {
  display: flex;
  align-items: center;
  gap: 8px;
  flex: 1;
  min-width: 0;
}

.filter-checkbox {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 14px;
  height: 14px;
  flex-shrink: 0;
  border-radius: 3px;
  border: 1px solid var(--border);
}

.filter-checkbox--checked {
  background: var(--accent);
  border-color: var(--accent);
  color: white;
}

.label-dot {
  width: 10px;
  height: 10px;
  border-radius: 50%;
  flex-shrink: 0;
}

.filter-item-text {
  font-size: 13px;
  min-width: 0;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
</style>
