// client/src/components/dashboard/SummaryBar.vue
<script setup lang="ts">
import { computed } from "vue";
import { Card, CardContent } from "@/components/ui/card";
import { useFleetSummary } from "@/composables/use-fleet-summary";

interface SummaryMetric {
  testId: string;
  label: string;
  value: string;
}

const { summary } = useFleetSummary();

const integerFormatter = new Intl.NumberFormat("en-US");
const currencyFormatter = new Intl.NumberFormat("en-US", {
  style: "currency",
  currency: "USD",
  minimumFractionDigits: 2,
  maximumFractionDigits: 2,
});

const metrics = computed<SummaryMetric[]>(() => {
  const currentSummary = summary.value;

  return [
    {
      testId: "summary-active-count",
      label: "Active",
      value: integerFormatter.format(currentSummary?.activeSessions ?? 0),
    },
    {
      testId: "summary-idle-count",
      label: "Idle",
      value: integerFormatter.format(currentSummary?.idleSessions ?? 0),
    },
    {
      testId: "summary-queued-count",
      label: "Queued",
      value: integerFormatter.format(currentSummary?.queuedTasks ?? 0),
    },
    {
      testId: "summary-tokens-count",
      label: "Tokens",
      value: integerFormatter.format(currentSummary?.totalTokens ?? 0),
    },
    {
      testId: "summary-cost-count",
      label: "Cost",
      value: currencyFormatter.format(currentSummary?.totalCost ?? 0),
    },
  ];
});
</script>

<template>
  <Card
    data-testid="summary-bar"
    class="border-border/80 bg-card/70 py-0 backdrop-blur-sm"
  >
    <CardContent class="grid gap-4 px-5 py-4 sm:grid-cols-2 xl:grid-cols-5">
      <div
        v-for="metric in metrics"
        :key="metric.testId"
        class="space-y-1 rounded-lg border border-border/60 bg-background/60 px-4 py-3"
      >
        <p class="text-xs font-medium uppercase tracking-[0.12em] text-muted-foreground">
          {{ metric.label }}
        </p>
        <p
          :data-testid="metric.testId"
          class="text-2xl font-semibold tracking-tight text-foreground"
        >
          {{ metric.value }}
        </p>
      </div>
    </CardContent>
  </Card>
</template>

// client/src/components/fleet/summary-bar.tsx
import { FleetSummary } from "@/lib/types";
import { formatTokens } from "@/lib/format-utils";
import {
  Zap,
  Pause,
  Hash,
  ListTodo,
} from "lucide-react";

interface SummaryBarProps {
  summary: FleetSummary;
}

export function SummaryBar({ summary }: SummaryBarProps) {
  const items = [
    {
      label: "Active",
      value: summary.activeSessions,
      icon: Zap,
      color: "text-green-500",
    },
    {
      label: "Idle",
      value: summary.idleSessions,
      icon: Pause,
      color: "text-muted-foreground",
    },
    {
      label: "Tokens",
      value: formatTokens(summary.totalTokens),
      icon: Hash,
      color: "text-purple-500",
    },
    {
      label: "Queued",
      value: summary.queuedTasks,
      icon: ListTodo,
      color: "text-orange-500",
    },
  ];

  return (
    <div className="grid grid-cols-2 gap-2 sm:grid-cols-4 sm:gap-3" data-testid="summary-bar">
      {items.map((item) => (
        <div
          key={item.label}
          className="flex flex-col items-center rounded-lg border bg-card p-2 sm:p-3 text-center"
          data-testid={`summary-${item.label.toLowerCase()}`}
        >
          <item.icon className={`h-4 w-4 ${item.color}`} />
          <span className="mt-1 text-lg font-semibold" data-testid={`summary-${item.label.toLowerCase()}-count`}>{item.value}</span>
          <span className="text-xs text-muted-foreground">{item.label}</span>
        </div>
      ))}
    </div>
  );
}
