// client/src/components/TauriUpdateDialog.vue
<script setup lang="ts">
import { computed, onMounted, onUnmounted, shallowRef } from "vue";
import type { Component } from "vue";
import { AlertCircle, Download, RefreshCw } from "lucide-vue-next";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Progress } from "@/components/ui/progress";
import {
  isTauri,
  tauriGetUpdateState,
  tauriInvoke,
  tauriListen,
  tauriSetUpdatePreferences,
} from "@/lib/tauri";
import { useUpdatePreferences } from "@/lib/update-preferences";

interface UpdateAvailablePayload {
  version: string;
  current_version: string;
}

interface UpdateProgressPayload {
  downloaded: number;
  total: number | null;
}

type UpdateDialogState = "idle" | "available" | "downloading" | "ready" | "error";

const [updatePreferences] = useUpdatePreferences();
const isTauriContext = isTauri();

const dialogState = shallowRef<UpdateDialogState>("idle");
const version = shallowRef("");
const currentVersion = shallowRef("");
const progress = shallowRef(0);
const errorMessage = shallowRef<string | null>(null);
const open = shallowRef(false);

const showDialog = computed(() => isTauriContext && dialogState.value !== "idle");
const isDownloading = computed(() => dialogState.value === "downloading");
const isReady = computed(() => dialogState.value === "ready");
const isError = computed(() => dialogState.value === "error");

const dialogTitle = computed(() => {
  if (dialogState.value === "error") {
    return "Update Failed";
  }

  if (dialogState.value === "ready") {
    return "Update Ready";
  }

  return "Update Available";
});

const dialogDescription = computed(() => {
  if (dialogState.value === "error") {
    return "Something went wrong while installing the update.";
  }

  if (dialogState.value === "ready") {
    return `Weave Fleet v${version.value} has been downloaded and will be applied on next start.`;
  }

  return `Weave Fleet v${version.value} is available (you have v${currentVersion.value}).`;
});

const statusIcon = computed<Component>(() => {
  if (dialogState.value === "error") {
    return AlertCircle;
  }

  return Download;
});

const statusIconClass = computed(() => {
  if (dialogState.value === "error") {
    return "h-5 w-5 text-destructive";
  }

  return "h-5 w-5";
});

function showUpdate(payload: UpdateAvailablePayload): void {
  version.value = payload.version;
  currentVersion.value = payload.current_version;
  dialogState.value = "available";
  open.value = true;
}

function setReadyState(payload: UpdateAvailablePayload): void {
  version.value = payload.version;
  currentVersion.value = payload.current_version;
  dialogState.value = "ready";
  open.value = true;
}

function handleUpdateAvailable(payload: UpdateAvailablePayload): void {
  if (!updatePreferences.autoUpdate) {
    showUpdate(payload);
    return;
  }

  version.value = payload.version;
  currentVersion.value = payload.current_version;
  dialogState.value = "downloading";
}

function handleOpenChange(nextOpen: boolean): void {
  if (nextOpen) {
    open.value = true;
    return;
  }

  if (dialogState.value === "downloading") {
    return;
  }

  open.value = false;
  dialogState.value = "idle";
}

async function handleInstall(): Promise<void> {
  if (!isTauriContext) {
    return;
  }

  dialogState.value = "downloading";
  progress.value = 0;
  errorMessage.value = null;

  try {
    await tauriInvoke("install_update");
  } catch (error) {
    errorMessage.value = error instanceof Error ? error.message : String(error);
    dialogState.value = "error";
  }
}

async function syncUpdatePreferences(): Promise<void> {
  if (!isTauriContext) {
    return;
  }

  try {
    await tauriSetUpdatePreferences(updatePreferences.autoUpdate, updatePreferences.channel);
  } catch {
    // Command unavailable or not ready; ignore and keep client preference.
  }
}

async function hydrateUpdateState(): Promise<void> {
  if (!isTauriContext) {
    return;
  }

  try {
    const updateState = await tauriGetUpdateState();

    if (updateState.update_available) {
      version.value = updateState.update_available.version;
      currentVersion.value = updateState.update_available.current_version;
      dialogState.value = updateState.download_in_progress ? "downloading" : "available";

      if (!updatePreferences.autoUpdate) {
        open.value = true;
      }
    }

    if (updateState.update_ready_for_restart) {
      dialogState.value = "ready";
      open.value = true;
    }
  } catch {
    // Ignore when command is unavailable.
  }
}

async function checkForPendingUpdate(): Promise<void> {
  if (!isTauriContext) {
    return;
  }

  try {
    const payload = await tauriInvoke<UpdateAvailablePayload | null>("check_for_update");

    if (payload && !updatePreferences.autoUpdate) {
      showUpdate(payload);
    }
  } catch {
    // Not in Tauri or command not available — ignore.
  }
}

const unlisteners = shallowRef<Array<() => void>>([]);

onMounted(() => {
  if (!isTauriContext) {
    return;
  }

  void syncUpdatePreferences();
  void hydrateUpdateState();
  void checkForPendingUpdate();

  void tauriListen<UpdateAvailablePayload>("update-available", (payload) => {
    handleUpdateAvailable(payload);
  }).then((unlisten) => {
    if (unlisten) {
      unlisteners.value = [...unlisteners.value, unlisten];
    }
  });

  void tauriListen<UpdateAvailablePayload>("update-ready-for-restart", (payload) => {
    setReadyState(payload);
  }).then((unlisten) => {
    if (unlisten) {
      unlisteners.value = [...unlisteners.value, unlisten];
    }
  });

  void tauriListen<UpdateProgressPayload>("update-download-progress", (payload) => {
    if (payload.total && payload.total > 0) {
      progress.value = Math.round((payload.downloaded / payload.total) * 100);
    }
  }).then((unlisten) => {
    if (unlisten) {
      unlisteners.value = [...unlisteners.value, unlisten];
    }
  });
});

onUnmounted(() => {
  for (const unlisten of unlisteners.value) {
    unlisten();
  }

  unlisteners.value = [];
});
</script>

<template>
  <Dialog
    v-if="showDialog"
    :open="open"
    @update:open="handleOpenChange"
  >
    <DialogContent
      class="sm:max-w-md"
      :show-close-button="!isDownloading"
    >
      <DialogHeader>
        <DialogTitle class="flex items-center gap-2">
          <component
            :is="statusIcon"
            :class="statusIconClass"
          />
          {{ dialogTitle }}
        </DialogTitle>
        <DialogDescription>
          {{ dialogDescription }}
        </DialogDescription>
      </DialogHeader>

      <div class="space-y-4 py-2">
        <div
          v-if="isDownloading"
          class="space-y-2"
        >
          <div class="flex items-center justify-between text-sm text-muted-foreground">
            <span class="flex items-center gap-1.5">
              <RefreshCw class="h-3.5 w-3.5 animate-spin" />
              Downloading update...
            </span>
            <span>{{ progress }}%</span>
          </div>
          <Progress :model-value="progress" />
          <p class="text-xs text-muted-foreground">
            {{ updatePreferences.autoUpdate
              ? "The update is downloading in the background."
              : "The app will restart automatically once the update is installed." }}
          </p>
        </div>

        <div
          v-if="isReady"
          class="rounded-md bg-emerald-500/10 p-3 text-sm text-emerald-700 dark:text-emerald-400"
        >
          Update downloaded. Restart the app to switch to v{{ version }}.
        </div>

        <div
          v-if="isError && errorMessage"
          class="rounded-md bg-red-500/10 p-3 text-sm text-red-600 dark:text-red-400"
        >
          {{ errorMessage }}
        </div>
      </div>

      <DialogFooter>
        <template v-if="dialogState === 'available'">
          <Button
            variant="outline"
            @click="handleOpenChange(false)"
          >
            Not Now
          </Button>
          <Button
            class="gap-1.5"
            @click="handleInstall"
          >
            <Download class="h-3.5 w-3.5" />
            Install &amp; Restart
          </Button>
        </template>

        <template v-else-if="dialogState === 'error'">
          <Button
            variant="outline"
            @click="handleOpenChange(false)"
          >
            Dismiss
          </Button>
          <Button
            class="gap-1.5"
            @click="handleInstall"
          >
            <RefreshCw class="h-3.5 w-3.5" />
            Retry
          </Button>
        </template>

        <Button
          v-else-if="dialogState === 'ready'"
          variant="outline"
          @click="handleOpenChange(false)"
        >
          Got it
        </Button>
      </DialogFooter>
    </DialogContent>
  </Dialog>
</template>

// client/src/components/tauri-update-dialog.tsx

import { useEffect, useState, useCallback } from "react";
import { Download, RefreshCw, AlertCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from "@/components/ui/dialog";
import {
  isTauri,
  tauriGetUpdateState,
  tauriListen,
  tauriInvoke,
  tauriSetUpdatePreferences,
} from "@/lib/tauri";
import { useUpdatePreferences } from "@/lib/update-preferences";

interface UpdateAvailablePayload {
  version: string;
  current_version: string;
}

interface UpdateProgressPayload {
  downloaded: number;
  total: number | null;
}

type UpdateState = "idle" | "available" | "downloading" | "ready" | "error";

function showUpdate(
  payload: UpdateAvailablePayload,
  setVersion: (v: string) => void,
  setCurrentVersion: (v: string) => void,
  setState: (s: UpdateState) => void,
  setOpen: (o: boolean) => void,
) {
  setVersion(payload.version);
  setCurrentVersion(payload.current_version);
  setState("available");
  setOpen(true);
}

export function TauriUpdateDialog() {
  const [updatePreferences] = useUpdatePreferences();
  const [state, setState] = useState<UpdateState>("idle");
  const [version, setVersion] = useState("");
  const [currentVersion, setCurrentVersion] = useState("");
  const [progress, setProgress] = useState(0);
  const [error, setError] = useState<string | null>(null);
  const [open, setOpen] = useState(false);
  useEffect(() => {
    if (!isTauri()) return;

    tauriSetUpdatePreferences(
      updatePreferences.autoUpdate,
      updatePreferences.channel,
    ).catch(() => {
      // Command unavailable or not ready; ignore and keep client preference.
    });
  }, [updatePreferences]);

  // Listen for the Rust-emitted "update-available" event AND poll for any
  // pending update that fired before the listener was registered.
  useEffect(() => {
    if (!isTauri()) return;

    tauriGetUpdateState()
      .then((updateState) => {
        if (updateState.update_available) {
          setVersion(updateState.update_available.version);
          setCurrentVersion(updateState.update_available.current_version);
          setState(updateState.download_in_progress ? "downloading" : "available");
          if (!updatePreferences.autoUpdate) {
            setOpen(true);
          }
        }

        if (updateState.update_ready_for_restart) {
          setState("ready");
          setOpen(true);
        }
      })
      .catch(() => {
        // Ignore when command is unavailable.
      });

    let cancelled = false;
    let unlisten: (() => void) | null = null;

    // Register event listener
    tauriListen<UpdateAvailablePayload>("update-available", (payload) => {
      if (!cancelled) {
        if (!updatePreferences.autoUpdate) {
          showUpdate(payload, setVersion, setCurrentVersion, setState, setOpen);
        } else {
          setVersion(payload.version);
          setCurrentVersion(payload.current_version);
          setState("downloading");
        }
      }
    }).then((fn) => {
      if (cancelled) {
        // Component unmounted before listener was registered — clean up immediately
        fn?.();
      } else {
        unlisten = fn;
      }
    });

    // Pull-based fallback: check for any pending update stored in Rust state.
    // This handles the race where the Rust event fires before the JS listener
    // is registered.
    tauriInvoke<UpdateAvailablePayload | null>("check_for_update")
      .then((payload) => {
        if (payload && !cancelled && !updatePreferences.autoUpdate) {
            showUpdate(payload, setVersion, setCurrentVersion, setState, setOpen);
        }
      })
      .catch(() => {
        // Not in Tauri or command not available — ignore
      });

    return () => {
      cancelled = true;
      unlisten?.();
    };
  }, [updatePreferences.autoUpdate]);

  useEffect(() => {
    if (!isTauri()) return;

    let cancelled = false;
    let unlisten: (() => void) | null = null;

    tauriListen<UpdateAvailablePayload>("update-ready-for-restart", (payload) => {
      if (!cancelled) {
        setVersion(payload.version);
        setCurrentVersion(payload.current_version);
        setState("ready");
        setOpen(true);
      }
    }).then((fn) => {
      if (cancelled) {
        fn?.();
      } else {
        unlisten = fn;
      }
    });

    return () => {
      cancelled = true;
      unlisten?.();
    };
  }, []);

  // Listen for download progress events
  useEffect(() => {
    if (!isTauri()) return;

    let cancelled = false;
    let unlisten: (() => void) | null = null;

    tauriListen<UpdateProgressPayload>(
      "update-download-progress",
      (payload) => {
        if (!cancelled && payload.total && payload.total > 0) {
          setProgress(Math.round((payload.downloaded / payload.total) * 100));
        }
      },
    ).then((fn) => {
      if (cancelled) {
        fn?.();
      } else {
        unlisten = fn;
      }
    });

    return () => {
      cancelled = true;
      unlisten?.();
    };
  }, []);

  const handleInstall = useCallback(async () => {
    if (!isTauri()) return;

    setState("downloading");
    setProgress(0);
    setError(null);

    try {
      await tauriInvoke("install_update");
      // If we get here, the app will restart — this line is unlikely to run
    } catch (e) {
      const message = e instanceof Error ? e.message : String(e);
      setError(message);
      setState("error");
    }
  }, []);

  const handleDismiss = useCallback(() => {
    if (state !== "downloading") {
      setOpen(false);
      // Reset state so the dialog can re-open on next check
      setState("idle");
    }
  }, [state]);

  // Don't render anything outside Tauri or when there's no update
  if (!isTauri() || state === "idle") return null;

  return (
    <Dialog open={open} onOpenChange={handleDismiss}>
      <DialogContent
        className="sm:max-w-md"
        showCloseButton={state !== "downloading"}
      >
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            {state === "error" ? (
              <AlertCircle className="h-5 w-5 text-red-500" />
            ) : (
              <Download className="h-5 w-5" />
            )}
            {state === "error"
              ? "Update Failed"
              : state === "ready"
                ? "Update Ready"
                : "Update Available"}
          </DialogTitle>
          <DialogDescription>
            {state === "error"
              ? "Something went wrong while installing the update."
              : state === "ready"
                ? `Weave Fleet v${version} has been downloaded and will be applied on next start.`
              : `Weave Fleet v${version} is available (you have v${currentVersion}).`}
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-4 py-2">
          {state === "downloading" && (
            <div className="space-y-2">
              <div className="flex items-center justify-between text-sm text-muted-foreground">
                <span className="flex items-center gap-1.5">
                  <RefreshCw className="h-3.5 w-3.5 animate-spin" />
                  Downloading update...
                </span>
                <span>{progress}%</span>
              </div>
              <Progress value={progress} />
              <p className="text-xs text-muted-foreground">
                {updatePreferences.autoUpdate
                  ? "The update is downloading in the background."
                  : "The app will restart automatically once the update is installed."}
              </p>
            </div>
          )}

          {state === "ready" && (
            <div className="rounded-md bg-emerald-500/10 p-3 text-sm text-emerald-700 dark:text-emerald-400">
              Update downloaded. Restart the app to switch to v{version}.
            </div>
          )}

          {state === "error" && error && (
            <div className="rounded-md bg-red-500/10 p-3 text-sm text-red-600 dark:text-red-400">
              {error}
            </div>
          )}
        </div>

        <DialogFooter>
          {state === "available" && (
            <>
              <Button variant="outline" onClick={handleDismiss}>
                Not Now
              </Button>
              <Button onClick={handleInstall} className="gap-1.5">
                <Download className="h-3.5 w-3.5" />
                Install &amp; Restart
              </Button>
            </>
          )}
          {state === "error" && (
            <>
              <Button variant="outline" onClick={handleDismiss}>
                Dismiss
              </Button>
              <Button onClick={handleInstall} className="gap-1.5">
                <RefreshCw className="h-3.5 w-3.5" />
                Retry
              </Button>
            </>
          )}
          {state === "ready" && (
            <Button variant="outline" onClick={handleDismiss}>
              Got it
            </Button>
          )}
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
