// client/src/components/ui/responsive-dialog.tsx

import * as React from "react";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import {
  Sheet,
  SheetContent,
  SheetHeader,
  SheetTitle,
  SheetTrigger,
} from "@/components/ui/sheet";
import { useIsMobile } from "@/hooks/use-media-query";

// ─── Props ──────────────────────────────────────────────────────────────────

interface ResponsiveDialogProps {
  open?: boolean;
  onOpenChange?: (open: boolean) => void;
  title: string;
  trigger?: React.ReactNode;
  /** Optional className forwarded to DialogContent / SheetContent */
  className?: string;
  children: React.ReactNode;
}

/**
 * Renders as a bottom Sheet on mobile and as a centered Dialog on desktop.
 * Drop-in replacement for simple form dialogs that need better mobile UX.
 */
export function ResponsiveDialog({
  open,
  onOpenChange,
  title,
  trigger,
  className,
  children,
}: ResponsiveDialogProps) {
  const isMobile = useIsMobile();

  if (isMobile) {
    return (
      <Sheet open={open} onOpenChange={onOpenChange}>
        {trigger && <SheetTrigger asChild>{trigger}</SheetTrigger>}
        <SheetContent side="bottom" className={className}>
          <SheetHeader>
            <SheetTitle>{title}</SheetTitle>
          </SheetHeader>
          <div className="overflow-y-auto max-h-[75vh] pb-safe-bottom">
            {children}
          </div>
        </SheetContent>
      </Sheet>
    );
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      {trigger && <DialogTrigger asChild>{trigger}</DialogTrigger>}
      <DialogContent className={className}>
        <DialogHeader>
          <DialogTitle>{title}</DialogTitle>
        </DialogHeader>
        {children}
      </DialogContent>
    </Dialog>
  );
}

// client/src/components/ui/responsive-dialog/ResponsiveDialog.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue";
import { useIsMobile } from "@/composables/use-media-query";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  Sheet,
  SheetContent,
  SheetDescription,
  SheetHeader,
  SheetTitle,
} from "@/components/ui/sheet";

const props = defineProps<{
  open?: boolean;
  title?: string;
  description?: string;
  class?: HTMLAttributes["class"];
}>();

const emit = defineEmits<{
  "update:open": [value: boolean];
}>();

const isMobile = useIsMobile();

function handleOpenChange(value: boolean): void {
  emit("update:open", value);
}
</script>

<template>
  <!-- Mobile: bottom sheet -->
  <Sheet
    v-if="isMobile"
    :open="props.open"
    @update:open="handleOpenChange"
  >
    <SheetContent
      side="bottom"
      :class="[
        'max-h-[calc(var(--visual-vh,100dvh)*0.75)] overflow-y-auto pb-[env(safe-area-inset-bottom,0px)]',
        props.class,
      ]"
    >
      <SheetHeader v-if="props.title || props.description">
        <SheetTitle v-if="props.title">
          {{ props.title }}
        </SheetTitle>
        <SheetDescription v-if="props.description">
          {{ props.description }}
        </SheetDescription>
      </SheetHeader>
      <slot />
    </SheetContent>
  </Sheet>

  <!-- Desktop: centered dialog -->
  <Dialog
    v-else
    :open="props.open"
    @update:open="handleOpenChange"
  >
    <DialogContent :class="props.class">
      <DialogHeader v-if="props.title || props.description">
        <DialogTitle v-if="props.title">
          {{ props.title }}
        </DialogTitle>
        <DialogDescription v-if="props.description">
          {{ props.description }}
        </DialogDescription>
      </DialogHeader>
      <slot />
    </DialogContent>
  </Dialog>
</template>
